### PR TITLE
Fix regression when opening an empty log history

### LINKED ISSUE #43933: Processing/History python error
On the latest master on Ubuntu 20.04, when trying to open an empty Processing/History dialog:

```
Traceback (most recent call last):
  File "/usr/share/qgis/python/plugins/processing/ProcessingPlugin.py", line 355, in openHistory
    dlg = HistoryDialog()
  File "/usr/share/qgis/python/plugins/processing/gui/HistoryDialog.py", line 90, in __init__
    self.fillTree()
  File "/usr/share/qgis/python/plugins/processing/gui/HistoryDialog.py", line 170, in fillTree
    self.tree.topLevelItem(0).setExpanded(True)
AttributeError: 'NoneType' object has no attribute 'setExpanded'
```

### PR DESCRIPTION
**Pull request by nicogodet**
## Description

Regression introduce by https://github.com/qgis/QGIS/pull/42649

`fillTree()` should be exited if no entry is found in `ProcessingLog.logFilename()`
Otherwise, `group_items = []` when `self.tree.addTopLevelItems(reversed(group_items))` causing an error when we try to expand the first top level item.

Fixes #43933

### CODE REVIEW

**Review by nirvn — APPROVED** [review]

**Comment by nicogodet** [comment]
Should be backported to 3.20
