### ISSUE TITLE
GDAL rasterize algorithm : add ALL_TOUCHED option

### ISSUE THREAD

**Issue by MathieuChailloux** [qgis/QGIS#33445]
**Feature description.**
GDAL rasterize command provides ALL_TOUCHED (-at) option to rasterize all pixels touched by lines or polygons.
This option is not available through QGIS processing algorithm (_processing/algs/gdal/rasterize.py_). Option is parsed in _getConsoleCommands_ but is not initialized in _initAlgorithm_.

**Possible fix**
A possible fix could be to add below code in _initAlgorithm_ 
```
        self.addParameter(
            QgsProcessingParameterBoolean(
                self.ALL_TOUCH,
                description = 'ALL_TOUCHED option',
                defaultValue=False,
                optional=True))
```

**Comment by alexbruy** [comment]
I'd say this is a won't-fix. You can pass any additional command-line options by specifying them in "Additional command-line parameters" field.

**Comment by gioman** [comment]
> I'd say this is a won't-fix. You can pass any additional command-line options by specifying them in "Additional command-line parameters" field.

yeah, we already turned down other similar feature requests.

**Comment by chrissampson2** [comment]
Hi all, I am trying to get this feature to work too, but seem completely unable to do so.  

> I'd say this is a won't-fix. You can pass any additional command-line options by specifying them in "Additional command-line parameters" field.

I apologise if I am fundamentally misunderstanding something here, but I can see no such field in the tool GUI?

**Comment by MathieuChailloux** [comment]
Ok, so I managed to get this working with EXTRA option in 3.11.0 version with something like

`parameters['EXTRA'] = '-at'`

Yet, I don't understand why ALL_TOUCH attribute is defined and parsed in _rasterize.py_ but not initialized. In my humble opinion, it should either be completely deleted either be properly intialized.

**Comment by chrissampson2** [comment]
Yes looks like it's been addressed for 3.11  Thank you very much for addressing this, it's a really important tool for us.
