### ISSUE TITLE
QGIS 3.13.0-Master "ImportError: cannot import name 'Authentication' from 'owslib.util'"

### ISSUE THREAD

**Issue by agiudiceandrea** [qgis/QGIS#37175]
**Describe the bug**

The following error is displayed with QGIS 3.13.0-Master (ce17f7fa78) on Windows 10 64 bit for the MetaSearch Plugin:

```
2020-06-12T19:16:05     CRITICAL    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 334, in _startPlugin
              plugins[packageName] = package.classFactory(iface)
              File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\MetaSearch\__init__.py", line 29, in classFactory
              from MetaSearch.plugin import MetaSearchPlugin
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\MetaSearch\plugin.py", line 34, in 
              from MetaSearch.dialogs.maindialog import MetaSearchDialog
              File "C:/OSGEO4~1/apps/qgis-dev/./python\qgis\utils.py", line 743, in _import
              mod = _builtin_import(name, globals, locals, fromlist, level)
              File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\MetaSearch\dialogs\maindialog.py", line 54, in 
              from owslib.util import Authentication
             ImportError: cannot import name 'Authentication' from 'owslib.util' (C:\OSGEO4~1\apps\Python37\lib\site-packages\owslib\util.py)
```
The MetaSearch Plugin cannot be enabled.

It seems the regression was introduced by commit 682c2000ade00ac8731d126e1920c1cb9b747424 PR https://github.com/qgis/QGIS/pull/36932

**QGIS and OS versions**

QGIS version
3.13.0-Master
QGIS code revision
ce17f7fa78
Compiled against Qt
5.11.2
Running against Qt
5.11.2
Compiled against GDAL/OGR
3.2.0dev
Running against GDAL/OGR
3.2.0dev
Compiled against GEOS
3.8.1-CAPI-1.13.3
Running against GEOS
3.8.1-CAPI-1.13.3
Compiled against SQLite
3.29.0
Running against SQLite
3.29.0
PostgreSQL Client Version
11.5
SpatiaLite Version
4.3.0
QWT Version
6.1.3
QScintilla2 Version
2.10.8
Compiled against PROJ
7.1.0
Running against PROJ
Rel. 7.1.0, August 1st, 2020
OS Version
Windows 10 (10.0)
This copy of QGIS writes debugging output.
Active python plugins
db_manager; 
processing

**Additional context**
Installed via OSGeo4W Network Installer (64 bit)
Relevant installed OSGeo4W packages versions:
qgis-dev-3.13.0-58
python3-owslib-0.17.0-1 / 2018-Oct-07 (latest available)

This regression was also reported for Ubuntu 18.04 (see https://github.com/qgis/QGIS/pull/36932#issuecomment-642248655 and https://github.com/qgis/QGIS/issues/37175#issuecomment-643431997)

**Comment by Houska1** [comment]
Just came here to report this and found @agiudiceandrea beat me to it.

I note that some old version (not sure which) of oswlib is installed by default by OSGeo4W, a version which doesn't have an owslib.util at all. Going back to the OSGeo4W installer, I can choose to manually install owslib 0.14, which has .util but no `Authentication` there. Looking briefly at oswlib on GitHub, it seems authentication code was refactored in 0.18 and the most recent version is 0.20.

**Comment by agiudiceandrea** [comment]
@Houska1, the latest python3-owslib package available on OSGeo4W 64 bit is 0.17.0-1, anyway it also has .util but no Authentication as the 0.14.0-1 version.

**Comment by DelazJ** [comment]
Authentication was [added last week](https://github.com/qgis/QGIS/pull/36932#issuecomment-642250016) , hence in version 0.20. And it's not a Windows-only issue. I wonder if a [version check](https://github.com/qgis/QGIS/pull/36932#issuecomment-638416862) as suggested by @nyalldawson wouldn't be a safer approach to deal with this issue

**Comment by agiudiceandrea** [comment]
OSWLib 0.20.0 now available on OSGeo4W https://trac.osgeo.org/osgeo4w/ticket/633

**Comment by nyalldawson** [comment]
This is fixed now
