### PR TITLE
Improve "avoid intersections" type awareness

### PR DESCRIPTION
**Pull request by m-kuhn**
## Description

When "avoid intersections" is enabled and the geometry type is changed (e.g. the last curve of a curvepolygon was removed), QGIS was giving a strange message "The operation would change the geometry type". This gives a) no helpful context for a user at all and b) is wrong because by saying it "would" it suggests that it attempted but did not change the geometry type, but it actually did change the geometry type.
In case of a single polygon being split into multiple polygons, the operation would actually create a multi geometry which cannot be saved.

With this change
1. the resulting geometry is coerced to the target geometry type.
2. in case of a single polygon being split into a multipolygon (or single line being split into multi line), it will now preserve only the biggest part (as often smaller parts are sliver polygons that better would be removed) and propose to restore the removed parts and insert them as new geometries for the cases where the user actually wants to preserve them.

Peek 2023-09-04 09-35

### CODE REVIEW

File: src/app/vertextool/qgsvertextool.cpp [hunk 1]
```diff
@@ -2427,11 +2427,52 @@ void QgsVertexTool::applyEditsToLayers( QgsVertexTool::VertexEdits &edits )
...
+            else // handle multi geometries
+            {
+              QgsFeatureList removedFeatures;
+              double largest = 0;
+              QgsFeature originalFeature = layer->getFeature( it2.key() );
+              int largestPartIndex = -1;
+              for ( int i = 0; i < newGeoms.size(); ++i )
+              {
+                QgsGeometry currentPart = newGeoms.at( i );
+                double currentPartSize = layer->geometryType() == Qgis::GeometryType::Polygon ? currentPart.area() : currentPart.length();
```
Comment (troopa81) [inline src/app/vertextool/qgsvertextool.cpp:2449]:
```suggestion
                const double currentPartSize = layer->geometryType() == Qgis::GeometryType::Polygon ? currentPart.area() : currentPart.length();
```

**Review by troopa81 — COMMENTED** [review]
I like the proposed behavior.

Could you add a test ? Not for the later paste part because it would be painful to test, but at least for the piece of code which keep the biggest part or coerce

**Review by uclaros — COMMENTED** [review]
Would you consider flipping the logic, ie default to adding the multiparts while proposing to delete them and only keep the largest part?

File: src/app/vertextool/qgsvertextool.cpp [hunk 2]
```diff
@@ -2427,11 +2427,52 @@ void QgsVertexTool::applyEditsToLayers( QgsVertexTool::VertexEdits &edits )
...
+                }
+              }
+              removedFeatures.removeAt( largestPartIndex );
+              QgsMessageBarItem *messageBarItem = QgisApp::instance()->messageBar()->createMessage( tr( "Avoid overlaps" ), tr( "Only the largest of multiple created geometries was preserved." ) );
+              QPushButton *restoreButton = new QPushButton( tr( "Restore others" ) );
+              connect( restoreButton, &QPushButton::clicked, restoreButton, [ = ]
+              {
+                layer->beginEditCommand( tr( "Restored geometry parts removed by avoid overlaps" ) );
+                QgsFeatureList unconstFeatures = removedFeatures;
+                QgisApp::instance()->pasteFeatures( layer, 0, removedFeatures.size(), unconstFeatures );
```
[the remark this answers is not in the document]
Comment (m-kuhn) [reply src/app/vertextool/qgsvertextool.cpp:2469]: It's taking care of all the constraints etc, that's why I chose this. If someone wants to improve topo logic for pasting features, that would eventually fix this.

**Comment by m-kuhn** [comment]
> Would you consider flipping the logic, ie default to adding the multiparts while proposing to delete them and only keep the largest part?

I think most of the time this will introduce undesired sliver polygons, I think defaulting to the "main" geometry is fine.

File: src/app/vertextool/qgsvertextool.cpp [hunk 3]
```diff
@@ -2427,11 +2427,52 @@ void QgsVertexTool::applyEditsToLayers( QgsVertexTool::VertexEdits &edits )
...
+              } );
+              messageBarItem->layout()->addWidget( restoreButton );
+              QgisApp::instance()->messageBar()->pushWidget( messageBarItem, Qgis::MessageLevel::Info, 5 );
```
[the remark this answers is not in the document]
Comment (m-kuhn) [reply src/app/vertextool/qgsvertextool.cpp:2472]: Feel free to propose something else, this was chosen based on other messages.

**Comment by troopa81** [comment]
> @troopa81 are you happy with the test like that?

Yes, thank you. and willing to merge if @uclaros is OK. 

I think the comment regarding the delay for displayed message is relevant but apply for all messages (maybe we should have a global parameter) and so is out of the scope of this PR. And I agree with your comment on topo points on pasted feature.

**Review by troopa81 — APPROVED** [review]

**Comment by m-kuhn** [comment]
@uclaros do you have any further comments or can this be merged?

File: src/app/vertextool/qgsvertextool.cpp (hunk 3 above)
[the remark this answers is not in the document]
Comment (DelazJ) [reply src/app/vertextool/qgsvertextool.cpp:2472]: 15s? or more ( _+ it is not sure it will get translated for the first times people will face it_)?
I may be wrong but I don't think that most (any?) of the other messages require an immediate decision from the user. They are mainly and simply informative.

[the remark this answers is not in the document]
Comment (m-kuhn) [reply src/app/vertextool/qgsvertextool.cpp:2472]:
```suggestion
              QgisApp::instance()->messageBar()->pushWidget( messageBarItem, Qgis::MessageLevel::Info, 15 );
```

**Comment by uclaros** [comment]
Hmm, the longer timeout doesn't feel right after all...
The user might still not notice the message, have it hidden by a subsequent message or worse, click the button after the layer has been removed resulting in a crash.

Maybe it would make sense to have a message box instead, similar to the "delete features outside your screen" confirmation. This would also allow for a longer explanation of what is happening.


Another thing that slightly bothers me is not matching the behavior between different tools, ie this _largest area/length part wins_ logic does not apply to the _new feature_ tool, but that's not a showstopper of course.

**Comment by m-kuhn** [comment]
I'm confident people will get used to this behavior.
If I am working on a (non-multi) polygon layer and I change the shape of a polygon in a way that it should be multiplied, I should expect something to happen and pay attention to this dialog.

I admit, I am not a fan of modal dialogs. Usually the next user comes and says "I don't want to see this, it gets into my way" which leads to a "do not show again" checkbox which then will force one specific behavior.

If there's a consensus I can adapt this PR with a modal dialog, are there more opinions? There would also be the option to fine tune this behavior later.

**Comment by troopa81** [comment]
> If there's a consensus I can adapt this PR with a modal dialog, are there more opinions? There would also be the option to fine tune this behavior later.

I'm not a great fan of modal dialog either but I don't have a strong opinion about what expect a *real* user in such situation (which doesn't happen very often ?)

**Comment by m-kuhn** [comment]
Good catch with the pointer check, added!
Also thank you all very much for the good in depth review code- and UX-wise.

**Comment by nyalldawson** [comment]
I'm not a fan of the auto-timeout disappearing message. Could we make it stay indefinitely instead? (It could be cleared as soon as the user starts the next edit operation to avoid stacking messages).

I'm concerned that a user will take some time to read and comprehend exactly what this message means, and in that time it will vanish and leave them clueless/frustrated.

**Comment by m-kuhn** [comment]
I can do that, how would you detect "starts the next edit operation"?

**Comment by uclaros** [comment]
> Maybe you could hook up to the `layer->undoStack()->indexChanged()` signal

hmmm, the signal is fired for the modification that triggered the message too, dismissing it immediately : /

**Comment by m-kuhn** [comment]
Too bad :-/

I could introduce a "only hide if newIndex != oldIndex +1", is it worth the complexity?

**Comment by nirvn** [comment]
@m-kuhn , this broke builds with the following error:

```
/home/webmaster/dev/cpp/QGIS/src/app/vertextool/qgsvertextool.cpp: In member function ‘void QgsVertexTool::applyEditsToLayers(VertexEdits&)’:
/home/webmaster/dev/cpp/QGIS/src/app/vertextool/qgsvertextool.cpp:2443:63: error: ‘it2’ was not declared in this scope
 2443 |               QgsFeature originalFeature = layer->getFeature( it2.key() );
      |                                                               ^~~
make[2]: *** [src/app/CMakeFiles/qgis_app.dir/build.make:1882: src/app/CMakeFiles/qgis_app.dir/vertextool/qgsvertextool.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/Makefile2:7898: src/app/CMakeFiles/qgis_app.dir/all] Error 2
make: *** [Makefile:166: all] Error 2
```

It's an accidental crossing of wires with another PT that was merged at the same time (https://github.com/qgis/QGIS/pull/53632/files#diff-2b5689cf92009403c1752885360323bc0a4abc6faa01bfd4f49293b9747d6254L2392) which removed it2 et al.

**Comment by agiudiceandrea** [comment]
@m-kuhn @nirvn, today new QGIS versions will be released by @jef-n. Shouldn't this issue be fixed before the release?

**Comment by m-kuhn** [comment]
I am on it
