### PR TITLE
[needs-qa]Fix QCA-ssl for FreeBSD

### PR DESCRIPTION
**Pull request by lbartoletti**
## Description
I need to use Qt5 macros on FreeBSD.

@dakcarto, as you are the author, can you take a look please?

Thanks.

## Checklist

> Reviewing is a process done by project maintainers, mostly on a volunteer basis. We try to keep the overhead as small as possible and appreciate if you help us to do so by completing the following items. Feel free to ask in a comment if you have troubles with any of them.

- [X] Commit messages are descriptive and explain the rationale for changes
- [ ] Commits which fix bugs include `fixes #11111` in the commit message next to the description
- [ ] Commits which add new features are tagged with `[FEATURE]` in the commit message
- [ ] Commits which change the UI or existing user workflows are tagged with `[needs-docs]` in the commit message and containt sufficient information in the commit message to be documented
- [X] I have read the [QGIS Coding Standards](https://docs.qgis.org/testing/en/docs/developers_guide/codingstandards.html) and this PR complies with them
- [ ] This PR passes all existing unit tests (test results will be reported by travis-ci after opening this PR)
- [ ] New unit tests have been added for core changes
- [ ] I have run [the `scripts/prepare-commit.sh` script](https://github.com/qgis/QGIS/blob/master/.github/CONTRIBUTE.md#contributing-to-qgis) before each commit

### CODE REVIEW

**Comment by lbartoletti** [comment]
Travis is Happy, BSD too, but linux not... On a testing debian, I've the same error as @m-kuhn some [years ago](https://stackoverflow.com/questions/40761777/how-to-pass-fpic-in-a-try-run-command)...

Any idea?

**Comment by m-kuhn** [comment]
@lbartoletti Have a look at this commit which was done around this time ... d559d7ff2525072efa02ca376c498250d2143fd5

**Comment by lbartoletti** [comment]
@m-kuhn for FreeBSD cmake returns "Found QCA OpenSSL plugin" 👍 and it builds.

Is it ok for linux and others?

**Comment by m-kuhn** [comment]
I must admit, I've got no idea. If you have the time to investigate properly, that would be very much appreciated, if not, can you implement a fix that just works for FreeBSD?

**Comment by nyalldawson** [comment]
Let's just merge. Travis is happy, so if there is specific issues on other Linux platforms we'll only identify those after merge.

**Comment by saberraz** [comment]
This breaks my build:
```
[1/2] Building CXX object CMakeFiles/cmTC_f564f.dir/qcaossl.cpp.o
FAILED: CMakeFiles/cmTC_f564f.dir/qcaossl.cpp.o 
/usr/bin/c++   -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++ -I/usr/include/QtCrypto -fPIE   -std=gnu++11 -o CMakeFiles/cmTC_f564f.dir/qcaossl.cpp.o -c qcaossl.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:43:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:48,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /usr/include/QtCrypto/qca_core.h:36,
                 from /usr/include/QtCrypto/qca.h:36,
                 from /usr/include/QtCrypto/QtCrypto:1,
                 from qcaossl.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1135:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^~~~~
ninja: build stopped: subcommand failed.

CMake Error at cmake/QCAMacros.cmake:62 (message):
  QCA OpenSSL plugin not found (run-time/unit-test dependency)
Call Stack (most recent call first):
  CMakeLists.txt:361 (FIND_QCAOSSL_PLUGIN_CPP)

```

**Comment by lbartoletti** [comment]
@m-kuhn @nyalldawson can you revert it or fix it for linux? See comments from @rouault [here](https://github.com/qgis/QGIS/commit/25ba36180cfbf836b9458beb98e28f62349c4260#commitcomment-29193928) and @saberraz 

Regards.

**Comment by rouault** [comment]
Ugly (my cmake deeply sucks) and probably not portable on on-Unix targets, but the following works for me to fix the build on Ubuntu 16.04.  In addition to the manual -fPIC, -DCMAKE_POSITION_INDEPENDENT_CODE=ON has to be removed since the presence of -fPIC -fPIE doesn't work

```
diff --git a/cmake/QCAMacros.cmake b/cmake/QCAMacros.cmake
index b0196ce..cf87b08 100644
--- a/cmake/QCAMacros.cmake
+++ b/cmake/QCAMacros.cmake
@@ -42,16 +42,19 @@ function(FIND_QCAOSSL_PLUGIN_CPP PLUGIN_REQUIRED)
     set(QCA_INCLUDE_DIRECTORIES "-DINCLUDE_DIRECTORIES:STRING=${Qt5Core_INCLUDE_DIRS};${QCA_INCLUDE_DIR}")
     get_target_property(_QtCore_path Qt5::Core LOCATION)
     set(QCA_LINK_LIBRARIES "-DLINK_LIBRARIES:STRING=${_QtCore_path};${QCA_LIBRARY}")
+    SET(CMAKE_CXX_FLAGS_BACKUP "${CMAKE_CXX_FLAGS}")
+    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
 
     try_run(RUN_RESULT COMPILE_RESULT
       ${CMAKE_BINARY_DIR} ${TESTCPP}
       CMAKE_FLAGS "-DCMAKE_CXX_STANDARD=11"
-                  "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
                   "${QCA_INCLUDE_DIRECTORIES}"
                   "${QCA_LINK_LIBRARIES}"
       COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
     )
 
+    SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_BACKUP}")
+
     set(_msg "QCA OpenSSL plugin not found (run-time/unit-test dependency)")
 
     if(NOT COMPILE_RESULT)
```

**Comment by m-kuhn** [comment]
@rouault which compiler are you using?

**Comment by m-kuhn** [comment]
I was just looking at the cmake code and I think it only adds PIC if there is no PIE for a compiler available.

https://github.com/Kitware/CMake/blob/master/Source/cmLocalGenerator.cxx#L1838-L1856

And gcc defines it here as PIE only
https://github.com/Kitware/CMake/blob/master/Modules/Compiler/GNU.cmake#L18

Do you think the second one should be corrected and changed to `-fPIC -fPIE` upstream?

**Comment by rouault** [comment]
Not too sure about cmake definitions, but it looks like something specific with qtglobal.h (QT 5.5 here, but still the same upstream https://github.com/qt/qtbase/blob/e843e3bb00d26c841bd7132c00779c085368eab3/src/corelib/global/qglobal.h#L1186 )

```
#if !defined(QT_BOOTSTRAPPED) && defined(QT_REDUCE_RELOCATIONS) && defined(__ELF__) && \
    (!defined(__PIC__) || (defined(__PIE__) && defined(Q_CC_GNU) && Q_CC_GNU >= 500))
#  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
         "Compile your code with -fPIC (-fPIE is not enough)."
#endif
```
which means that with gcc >=5, it explicitly bails out if -fPIE is defined, even if -fPIC is also defined
Slightly lesser ugly patch, that basically adds a GCC specific code path
```
diff --git a/cmake/QCAMacros.cmake b/cmake/QCAMacros.cmake
index b0196ce..8e54965 100644
--- a/cmake/QCAMacros.cmake
+++ b/cmake/QCAMacros.cmake
@@ -43,14 +43,29 @@ function(FIND_QCAOSSL_PLUGIN_CPP PLUGIN_REQUIRED)
     get_target_property(_QtCore_path Qt5::Core LOCATION)
     set(QCA_LINK_LIBRARIES "-DLINK_LIBRARIES:STRING=${_QtCore_path};${QCA_LIBRARY}")
 
-    try_run(RUN_RESULT COMPILE_RESULT
-      ${CMAKE_BINARY_DIR} ${TESTCPP}
-      CMAKE_FLAGS "-DCMAKE_CXX_STANDARD=11"
-                  "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
-                  "${QCA_INCLUDE_DIRECTORIES}"
-                  "${QCA_LINK_LIBRARIES}"
-      COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
-    )
+    IF ("${CMAKE_CXX_COMPILER_ID}" MATCHES "GNU")
+        SET(CMAKE_CXX_FLAGS_BACKUP "${CMAKE_CXX_FLAGS}")
+        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -fPIC")
+        try_run(RUN_RESULT COMPILE_RESULT
+                ${CMAKE_BINARY_DIR} ${TESTCPP}
+                CMAKE_FLAGS "-DCMAKE_CXX_STANDARD=11"
+                            "${QCA_INCLUDE_DIRECTORIES}"
+                            "${QCA_LINK_LIBRARIES}"
+                COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
+        )
+        SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS_BACKUP}")
+    ELSE()
+        try_run(RUN_RESULT COMPILE_RESULT
+            ${CMAKE_BINARY_DIR} ${TESTCPP}
+            CMAKE_FLAGS "-DCMAKE_CXX_STANDARD=11"
+                        "-DCMAKE_POSITION_INDEPENDENT_CODE=ON"
+                        "${QCA_INCLUDE_DIRECTORIES}"
+                        "${QCA_LINK_LIBRARIES}"
+            COMPILE_OUTPUT_VARIABLE COMPILE_OUTPUT
+        )
+    ENDIF()
+
+    #
 
     set(_msg "QCA OpenSSL plugin not found (run-time/unit-test dependency)")
 
```

**Comment by m-kuhn** [comment]
Wow, thanks @rouault !

@lbartoletti can you incorporate this?
