### ISSUE TITLE
error when building for conda-forge

### ISSUE THREAD

**Issue by izahn** [qgis/QGIS#44859]
### What is the bug or the crash?

When building version 3.18 for conda-forge we see

```
$SRC_DIR/src/gui/raster/qgsrasterhistogramwidget.cpp:1047:37: error: invalid use of incomplete type 'const class QwtScaleDiv'
```
The full log can be found at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=368262&view=logs&j=4f922444-fdfe-5dcf-b824-02f86439ef14&t=b2a8456a-fb11-5506-ca32-5ccd32538dc0&l=3621

### Steps to reproduce the issue

Build the conda-forge package from https://github.com/regro-cf-autotick-bot/qgis-feedstock/tree/rebuild-proj801-0-1_h72f8d5

### Versions

3.18.3 (I know this is old, conda-forge is working on 3.20 but we need to update qt first).

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

I think maybe https://github.com/qgis/QGIS/blob/final-3_18_3/src/gui/raster/qgsrasterhistogramwidget.cpp needs
```
#include "qwt_polar_plot.h"
```
or so

**Comment by izahn** [comment]
This was due to trying to build with `qwt 6.2`, building with `qwt 6.1` worked as expected. Closing this since I believe it is fixed in `qgis 3.20` anyway.
