### ISSUE TITLE
Unable to Install Latest Release or Long Term Release on Pop!OS (Ubuntu 22.04 jammy)

### ISSUE THREAD

**Issue by gregorywaynepower** [qgis/QGIS#60815]
### What is the bug or the crash?

Hey Folks,

I want to make sure I'm not misreading the [Roadmap](https://qgis.org/resources/installation-guide/#repositories). Is jammy no longer supported? I've followed the [installation instructions](https://qgis.org/resources/installation-guide/#debian--ubuntu) as listed.

I'm unable to update to either the Latest or LTR releases. I also can't find a version of QGIS past 3.40.3 on https://ubuntu.qgis.org/ubuntu/dists/jammy/main/binary-amd64/Packages.

### Steps to reproduce the issue

I've followed the [installation instructions](https://qgis.org/resources/installation-guide/#debian--ubuntu) as listed.

### Versions

Unable to update to newest QGIS release.

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

**Comment by agiudiceandrea** [comment]
For release-3_40 is still 3.12

**Comment by gregorywaynepower** [comment]
> It may be because of CMake version.
> Ping @jef-n 

Is this something I need to update on my side of the fence?

**Comment by agiudiceandrea** [comment]
@gregorywaynepower, currently the QGIS packages of the latest QGIS versions are not available in any https://qgis.org/ repository, so you cannot install QGIS on Ubuntu 20.04 jammy form those repositories.

Alternatively you could install QGIS in other ways, e.g.: https://qgis.org/resources/installation-guide/#flatpak, https://qgis.org/resources/installation-guide/#spack, https://qgis.org/resources/installation-guide/#distrobox--toolbx.

**Comment by gregorywaynepower** [comment]
@agiudiceandrea Has this always been the case? I've used the ubuntugis or ubuntugis-unstable in the past to get a more up-to-date version of QGIS.

**Comment by lorenzogrv** [comment]
Same problem here. It's available for recent versions, i.e. noble, but does not for jammy.
Shouldn't it be available as stated at <https://qgis.org/resources/installation-guide/#available-codenames>?

**Comment by agiudiceandrea** [comment]
@jef-n, I know that QGIS version >= 3.42 are not available on Ubuntu 22.04 jammy due to increased menimun CMAKE version to 3.23 (https://github.com/qgis/QGIS/pull/60048#issuecomment-2605593700). Anyway the minimum required CMAKE version for release-3_40 is still 3.12 https://github.com/qgis/QGIS/blob/8b9c31417d08fc4958e7cf4f552624788cb0fd24/CMakeLists.txt#L3 so QGIS LTR 3.40 should be still available for jammy (which has CMAKE 3.22).
If it will not be available for any other reason, shouldn't https://qgis.org/resources/installation-guide/#repositories be updated reflecting the actual Debian and Ubuntu distribution for which QGIS is available?

**Comment by lorenzogrv** [comment]
Some context:

```bash
$ cat /etc/apt/sources.list.d/qgis.sources 
Types: deb deb-src
URIs: https://qgis.org/ubuntu-ltr
Suites: jammy
Architectures: amd64
Components: main
Signed-By: /etc/apt/keyrings/qgis-archive-keyring.gpg
```

```bash
$ cat /etc/os-release 
NAME="Linux Mint"
VERSION="21.1 (Vera)"
ID=linuxmint
ID_LIKE="ubuntu debian"
PRETTY_NAME="Linux Mint 21.1"
VERSION_ID="21.1"
HOME_URL="https://www.linuxmint.com/"
SUPPORT_URL="https://forums.linuxmint.com/"
BUG_REPORT_URL="http://linuxmint-troubleshooting-guide.readthedocs.io/en/latest/"
PRIVACY_POLICY_URL="https://www.linuxmint.com/"
VERSION_CODENAME=vera
UBUNTU_CODENAME=jammy
```

```bash
$ apt update
# ...
$ apt-cache madison qgis
      qgis | 1:3.34.15+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.14+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.13+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.12+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.11+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.10+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.9+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.8+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.7+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.6+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.5+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.34.4+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.28.15+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.28.14+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.28.13+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 1:3.28.12+36jammy | https://qgis.org/ubuntu-ltr jammy/main amd64 Packages
      qgis | 3.22.4+dfsg-3build1 | http://archive.ubuntu.com/ubuntu jammy/universe amd64 Packages
      qgis | 1:3.34.15+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.14+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.13+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.12+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.11+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.10+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.9+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.8+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.7+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.6+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.5+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.34.4+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.28.15+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.28.14+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.28.13+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
      qgis | 1:3.28.12+36jammy | https://qgis.org/ubuntu-ltr jammy/main Sources
```

**Comment by jef-n** [comment]
```
# apt-cache policy qgis
qgis:
  Installed: …
  Candidate: 1:3.40.4+36jammy-1
  Version table:
     1:3.40.4+36jammy-1 500
        500 https://qgis.org/debian-ltr jammy/main amd64 Packages
```

**Comment by Alex-Kent** [comment]
FWIW, the current QGIS source (https://github.com/qgis/QGIS/commit/9a1d4532d129b0c4a02cf3956bd4be887d371cd1) compiles fine on Ubuntu Jammy (22.04.5 LTS) provided two changes are made:

1. Running `cmake ..` fails with the error:
    > <code>CMake Error at CMakeLists.txt:3 (cmake_minimum_required):</code>
  <code>CMake 3.23.0 or higher is required.  You are running version 3.22.1</code>
    
    To fix this change line 3 of `CMakeLists.txt` to:
    `cmake_minimum_required(VERSION 3.22.0)`
    
    [This is the issue discussed in this bug report.]

2. Running `make` fails with the following error:
    > <code>sip-build: An internal error occurred...</code>
    …
    <code>AttributeError: 'ScopedName' object has no attribute 'replace'</code>
    …
    
    To fix this change line 437 of `/usr/lib/python3/dist-packages/sipbuild/generator/parser/instantiations.py` to:
    `i_name = ScopedName.parse(template_string(proto_name.base_name, expansions))`
    
    See https://github.com/qgis/QGIS/issues/49214 for details.

**Comment by gregorywaynepower** [comment]
@Alex-Kent Is this for the Long Term Stable release, or the Stable release?

**Comment by Alex-Kent** [comment]
@gregorywaynepower > Is this for the Long Term Stable release, or the Stable release?

I tested using the latest Git version of the code; i.e. what will become the next Stable release.  I didn't test building the code for any of the LTR releases nor for the current Stable release.  Both of those errors are Ubuntu (and maybe Debian, etc.) specific/related so the fixes would probably also apply to the non-development QGIS branches.

**Comment by gregorywaynepower** [comment]
@Alex-Kent Awesome! I was hoping I wouldn't have to go down to Long Term Stable release? So you're telling me I should expect Stable (qgis and qgis-plugin-grass) to be installable on Ubuntu 22.04 LTS?

I've tried downgrading to `qgis-ltr` and I've ran into issues with `qgis-plugin-grass` depending on `grass787`, even though `grass (7.8.7-1)` is able to be installed--it seems like `qgis-plugin-grass` isn't able to see it as `grass787`.

**Comment by Alex-Kent** [comment]
@gregorywaynepower Regarding grass, I couldn't say.  I've been building from source only for submitting bug fixes, etc. and my builds don't include grass (presumably because I don't have its headers installed).  For production use I'm currently running a binary LTR release.

**Comment by gregorywaynepower** [comment]
@Alex-Kent The reason I ask is because it's a dependency of `qgis-plugin-grass` and is listed under the [installation instructions for Debian/Ubuntu](https://qgis.org/resources/installation-guide/#debian--ubuntu).

I do use the GRASS modules from QGIS as well. Are you saying you only use QGIS's Long Term Stable from https://qgis.org/ubuntu-ltr and only install `qgis`?

I've attempted only installing the Long Term Stable release and I'm stuck with qgis unable to be installed due to `qgis-providers` unable to be configured by dpkg:

```
Setting up qgis-providers (1:3.40.4+36jammy-1) ...
Segmentation fault (core dumped)
dpkg: error processing package qgis-providers (--configure):
 installed qgis-providers package post-installation script subprocess returned error exit status 139
Errors were encountered while processing:
 qgis-providers
```

I am able to launch qgis though, oddly enough.

**Comment by Alex-Kent** [comment]
I'm using the Ubuntu-provided QGIS and GRASS packages for Ubuntu 22.04.5 LTS.  Here's the apropos packages that I have installed:

 | Package | Version | Status | Maintainer |
|---|---|---|---|
| grass-core | 7.8.7-1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| grass-dev | 7.8.7-1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| grass-doc | 7.8.7-1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libgdal-grass | 3.4.1-3 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-3d3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-analysis3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-app3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-core3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-customwidgets | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgisgrass7-3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-gui3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-native3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgispython3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| libqgis-server3.22.4 | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| python3-qgis | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| python3-qgis-common | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-common | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-plugin-grass | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-plugin-grass-common | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-provider-grass | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-providers | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |
| qgis-providers-common | 3.22.4+dfsg-3build1 | install ok installed | Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com> |


The above was generated using:
```sh
echo '| Package | Version | Status | Maintainer |' ; echo '|---|---|---|---|' ; for p in grass-core grass-dev grass-doc libgdal-grass libqgis-3d3.22.4 libqgis-analysis3.22.4 libqgis-app3.22.4 libqgis-core3.22.4 libqgis-customwidgets libqgisgrass7-3.22.4 libqgis-gui3.22.4 libqgis-native3.22.4 libqgispython3.22.4 libqgis-server3.22.4 python3-qgis python3-qgis-common qgis qgis-common qgis-plugin-grass qgis-plugin-grass-common qgis-provider-grass qgis-providers qgis-providers-common ; do m=$( dpkg -s $p | grep -E '^Maintainer:' | sed -E 's/^.*?: //' ) ; v=$( dpkg -s $p | egrep '^Version:' | sed -E 's/^.*?: //' ) ; s=$( dpkg -s $p | egrep '^Status:' | sed -E 's/^.*?: //' ) ; echo '| '$p' | '$v' | '$s' | '$m' |' ; done
```

I checked through my notes and see that I didn't have to do anything special to install the QGIS or GRASS binaries or libraries.

**Comment by Alex-Kent** [comment]
@gregorywaynepower I was mistaken when I said that building from source doesn't include GRASS support.  It does include support for GRASS 7 (but not GRASS 8) using the Ubuntu-supplied GRASS libraries and headers.  The build was performed using the modifications I mentioned earlier.  The build commands are (from memory):

```sh
git clone https://github.com/qgis/QGIS.git
mkdir build
cd build
cmake ../QGIS
make -j$(nproc)
```

**Comment by Alex-Kent** [comment]
> from `qgis --version`:
> 
> ```
> QGIS 3.40.4-Bratislava 'Bratislava' (4dd7d7e9691)
> ```

It sounds like you're using the QGIS-maintained Ubuntu packages, not the Ubuntu-maintained ones.  FWIW, the version of QGIS that my `jammy` install has is `QGIS 3.22.4-Białowieża 'Białowieża' (exported)`.

**Comment by Alex-Kent** [comment]
And for completeness, the output when built from source (run from the `build` directory):

```sh
$ ./output/bin/qgis --version
QGIS 3.43.0-Master 'Master' (8ea86e8ab0)
```

**Comment by gregorywaynepower** [comment]
@Alex-Kent I appreciate the follow-up. I was able to install QGIS-LTR from https://qgis.org/ubuntugis-ltr if I had GRASS installed from https://ppa.launchpadcontent.net/ubuntugis/ubuntugis-unstable/ubuntu/ added to my list of repositories `apt` could pull from. It's the one listed under Ubuntu from [GRASS GIS's installation instructions for Linux](https://grass.osgeo.org/download/linux/).

However, I know something is still up with `apt` or `dpkg` because if I throw the `sudo apt remove grass` command, I'm still able to access `grass`. They're both grass version 8.4.1. But that's probably just a coincidence.

**Comment by agiudiceandrea** [comment]
@suricactus , if you want to install QGIS LTR 3.40.4 you need to use the debian-ltr repository.
