### ISSUE TITLE
Cannot compile a QGIS application in C++ since 3.44 + QT6

### ISSUE THREAD

**Issue by stoffy28** [qgis/QGIS#64058]
### What is the bug or the crash?

I have downloaded QGIS 3.44 + Qt6 packages with OSGeo4W:

I try to compile the following code:

```
#include "qgsapplication.h"
#include "qgsjsonutils.h"
#include "qgsfeature.h"
#include "qgspoint.h"
        
int main(int argc, char** argv)
{
    QgsApplication* myApp = new QgsApplication(argc, argv, true, QString("C\\Temp"), "desktop");
    
    QgsFeature f;

    QgsPoint p;

    QVariant dummy;
    QString formattedValue = QString::fromStdString(QgsJsonUtils::jsonFromVariant(dummy).dump());

    int retval = QgsApplication::exec();  // Run the application event loop
    myApp->exitQgis();

    return retval;
}
```

**First issue:**

1>------ Build started: Project: testQgisQt6, Configuration: Release x64 ------
1>testQgisQt6.cpp
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgis.h(6169,1): warning C4267: 'return': conversion from 'size_t' to 'uint', possible loss of data
1>(compiling source file 'testQgisQt6.cpp')
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgis.h(6170,1): warning C4267: 'return': conversion from 'size_t' to 'uint', possible loss of data
1>(compiling source file 'testQgisQt6.cpp')
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgspointxy.h(412,24): warning C4267: 'initializing': conversion from 'size_t' to 'uint', possible loss of data
1>(compiling source file 'testQgisQt6.cpp')
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgspointxy.h(412,17): warning C4267: 'initializing': conversion from 'size_t' to 'const uint', possible loss of data
1>(compiling source file 'testQgisQt6.cpp')
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgspointxy.h(413,24): warning C4267: 'initializing': conversion from 'size_t' to 'uint', possible loss of data
1>(compiling source file 'testQgisQt6.cpp')
1>C:\Produits\OSGeo4W\apps\qgis-qt6\include\qgspointxy.h(413,17): warning C4267: 'initializing': conversion from 'size_t' to 'const uint', possible loss of data

**Second issue:**

1>C:\Users\myname\source\repos\testQgisQt6\testQgisQt6.cpp(39,67): error C2027: use of undefined type 'nlohmann::json_abi_v3_11_3::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_3::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>,void>'
1>    C:\Produits\OSGeo4W\apps\qgis-qt6\include\nlohmann\json_fwd.hpp(51,7):
1>    see declaration of 'nlohmann::json_abi_v3_11_3::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_3::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>,void>'
1>C:\Users\myname\source\repos\testQgisQt6\testQgisQt6.cpp(39,82): error C2027: use of undefined type 'nlohmann::json_abi_v3_11_3::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_3::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>,void>'
1>    C:\Produits\OSGeo4W\apps\qgis-qt6\include\nlohmann\json_fwd.hpp(51,7):
1>    see declaration of 'nlohmann::json_abi_v3_11_3::basic_json<std::map,std::vector,std::string,bool,int64_t,uint64_t,double,std::allocator,nlohmann::json_abi_v3_11_3::adl_serializer,std::vector<uint8_t,std::allocator<uint8_t>>,void>'
1>Done building project "testQgisQt6.vcxproj" -- FAILED.

### Steps to reproduce the issue

Compile my sample code with Visual Studio 2022.

### Versions

3.44 + Qt6
3.99 + Qt6

### Supported QGIS version

- [x] I'm running a supported QGIS version according to [the roadmap](https://www.qgis.org/en/site/getinvolved/development/roadmap.html#release-schedule).

### New profile

- [ ] I tried with a new [QGIS profile](https://docs.qgis.org/latest/en/docs/user_manual/introduction/qgis_configuration.html#working-with-user-profiles)

### Additional context

The sample code compiles fine with QGIS 3.40 + Qt5.

**Comment by agiudiceandrea** [comment]
@stoffy28 , doe the issue still occurs?

**Comment by stoffy28** [comment]
Issue is solved now.
