### ISSUE TITLE
QGIS 3.10.11 can't load user scripts if MetaSearch Catalog Client is disabled

### ISSUE THREAD

**Issue by kadarivan** [qgis/QGIS#39911]
**Describe the bug**
If I disable MetaSearch Catalog Client plugin, QGIS can't load user scripts
Log messages for all scripts:
CRITICAL    Could not import script algorithm '[script name]' from 'C:\Users\[user]\AppData\Roaming\QGIS\QGIS3\profiles\[profile]\processing\scripts\[script].py'
             module 'importlib' has no attribute 'util'

**How to Reproduce**
1, create a new profile
2, 'Create New Script from Template...' and save it to [profile]\processing\scripts\ folder
3, restart QGIS -> script loaded
4, disable MetaSearch Catalog Client plugin
5, restart QGIS -> script not loaded and CRITICAL error logged.
6, enable MetaSearch Catalog Client plugin
7, restart QGIS -> script loaded

**QGIS and OS versions**

QGIS version | 3.10.11-A Coruña | QGIS code revision | d2171173e4
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 3.1.4 | Running against GDAL/OGR | 3.1.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.29.0 | Running against SQLite | 3.29.0
PostgreSQL Client Version | 11.5 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | Windows 10 (10.0)
Active python plugins | db_manager; processing

**Comment by gioman** [comment]
@kadarivan cannot confirm here on 3.16 on Linux. Does it work on 3.16 on Windows?

**Comment by roya0045** [comment]
3.16 on win 10, no issues with import. What are the dependencies of your script?

**Comment by kadarivan** [comment]
3.16 affected too. Both installed from osgeo4w.
I don't have any extra dependencies. This is the built-in template script:
[test1.zip](https://github.com/qgis/QGIS/files/5515369/test1.zip)

2020-11-10T07:49:25     CRITICAL    Could not import script algorithm 'test1' from 'C:\Users\kadari\AppData\Roaming\QGIS\QGIS3\profiles\test\processing\scripts\test1.py'
             module 'importlib' has no attribute 'util'

**Comment by gioman** [comment]
> 3.16 affected too. Both installed from osgeo4w.

@kadarivan tested on osgeo4w, can't confirm.

**Comment by kadarivan** [comment]
I installed QGIS LTR (3.10.11-1) from osgeo4w to another PC (Win10 Pro 2004), but the result is the same for me.
The original computer is Win10 Enterprise 1809.

**Comment by kadarivan** [comment]
I installed QGIS LTR from osgeo4w again, but this time I used the qgis-ltr-full meta package, instead of qgis-ltr package.
In this case the bug disappeared.

**Comment by roya0045** [comment]
Possible python dependencies issues?

**Comment by gioman** [comment]
> Possible python dependencies issues?

I agree.

**Comment by agiudiceandrea** [comment]
Hi @gioman and @roya0045,
I don't know what relationship there is between the MetaSearch Catalog Client plugin or the additional packages installed by qgis-ltr-full and the issue, anyway it seems to me the issue is related to how ScriptUtils.py imports and use the importlib util module
https://github.com/qgis/QGIS/blob/21908f09f5e6beef0224e19cc3308a8cafe2ab0d/python/plugins/processing/script/ScriptUtils.py#L27 and https://github.com/qgis/QGIS/blob/21908f09f5e6beef0224e19cc3308a8cafe2ab0d/python/plugins/processing/script/ScriptUtils.py#L64-L65

Substituting
```python
import importlib
```
with
```python
from importlib import util
```

and
```python
spec = importlib.util.spec_from_file_location(moduleName, filePath)
module = importlib.util.module_from_spec(spec)
```
with
```python
spec = util.spec_from_file_location(moduleName, filePath)
module = util.module_from_spec(spec)
```

in `[OSGeo4W install folder]\apps\qgis-ltr\python\plugins\processing\script\ScriptUtils.py`

fixes the issue.

If @kadarivan could confirm I'll submit PR.

**Comment by kadarivan** [comment]
@agiudiceandrea yes, this patch fixed the bug. Thanks!
