### ISSUE TITLE
Build failure with sip 4.19.14

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29053]
Author Name: **Antonio Rojas** (Antonio Rojas)
Original Redmine Issue: [21235](https://issues.qgis.org/issues/21235)
Affected QGIS version: 3.4.4
Redmine category:build/install

---
After updating sip to 4.19.14 build fails with

/build/qgis/src/build/python/gui/sip_guipart3.cpp:172890:10: error: ‘void sipQgsAttributeFormRelationEditorWidget::createSearchWidgetWrappers()’ marked ‘override’, but does not override
 
          ^                         
/build/qgis/src/build/python/gui/sip_guipart3.cpp:176571:10: error: ‘void sipQgsAttributeFormEditorWidget::createSearchWidgetWrappers()’ marked ‘override’, but does not override
 
          ^

**Comment by alexbruy** [comment]
Please test with latest master, should be fixed already

**Comment by alexbruy** [comment]
Closed for the lack of feedback.
