### PR TITLE
Add bound-checking QgsAbstractGeometry::fromWkb and WkbPtr

### PR DESCRIPTION
**Pull request by strk**
Keeps old methods as deprecated.
This is unfinished.

The aim is fixing the test in #2722 with the new code.

Current problem is with adding the deprecated wrappers: trying to avoid to duplicate the wrapper in all levels of the inheritance hierarchy but SIP seems to be not happy with that:

```
/usr/src/qgis/build/master/python/core/sip_corepart0.cpp:34066:40: error: no matching function for call to ‘sipQgsPolygonV2::fromWkb(const unsigned char*&)’
```

Do I just have to re-generate sip bindings ?

### CODE REVIEW

**Comment by strk** [comment]
SIP bindings figured, but due to unit tests I'll have to duplicate the DEPRECATED wrapper methods for each and every QgsAbstractGeometryV2 subclass

**Comment by strk** [comment]
Is Q_DECL_DEPRECATED enough to mark pythong bindings deprecation ? Or how is it done on that side ?

**Comment by jef-n** [comment]
sip bindings are not generated.

We also have stuff that advances and returns wkb pointers (eg. _getPoint/_getLineString/_getPolygon; w/o updating keeping the length information).   [wkb-bounds-check](/jef-n/QGIS/tree/wkb-bounds-check) does address this.

**Comment by strk** [comment]
@jef-n please let me know if you intend to continue with your branch, it's silly to do the same work twice. I like your approach (passing around a WkbPtr) more than mine, anyway, so if you will complete that work in time for 2.14 I'll move to something else and let you deal with this (and #2722)

**Comment by jef-n** [comment]
To me bc4d16e is the fix and this is an improvement/feature.

**Comment by strk** [comment]
#2722 clearly shows there's another crash pending, or are you saying QgsGeometry::fromWkb is not part of the API ?

**Comment by strk** [comment]
Closing in favor of #2748
