### ISSUE TITLE
Qt6 build warns about: QgsGrassDataFile::open hides overloaded virtual function

### ISSUE THREAD

**Issue by t0b3** [qgis/QGIS#47937]
### What is the bug or the crash?

*as a developer* 
building Qt6 with GRASS8 warns about
```
/root/QGIS/src/providers/grass/qgsgrassdatafile.h:42:10: error: 'QgsGrassDataFile::open' hides overloaded virtual function [-Werror,-Woverloaded-virtual]
    bool open( FILE *fh );
         ^
```
https://github.com/qgis/QGIS/blob/e338d8d0e43b8cef6c999ac1d0181cf43006b3cb/src/providers/grass/qgsgrassdatafile.h#L42
see https://cdash.orfeo-toolbox.org/viewBuildError.php?buildid=94421

### Steps to reproduce the issue

compile `WITH_QT6=ON` and `WITH_GRASS8=ON` same as in #47887 - but set `WERROR=false`

### Versions

2.24.1 and master

### Supported QGIS version

- [ ] I'm running a supported QGIS version according to the roadmap.

### New profile

- [ ] I tried with a new QGIS profile

### Additional context

not asking for support, just an issue tracker for developers

**Comment by t0b3** [comment]
@blazek is 'QgsGrassDataFile::open' overloaded virtual function still needed for Qt6?
introduced by https://github.com/qgis/QGIS/commit/26588b59d1a170084dd5b0b615002e3d77ed203a#diff-844b936fec510817cde846acd882b75d8d1553eeb584b67cbac25bab8caabc95

**Comment by blazek** [comment]
Probably it is still needed.

Your fix with using QFile::open; should be sufficient.
