### ISSUE TITLE
MetaSearch 'NoneType' object has no attribute 'addRasterLayer'

### ISSUE THREAD

**Issue by overkamp** [qgis/QGIS#34759]
I get the python error
'NoneType' object has no attribute 'addRasterLayer'
in function add_to_ows in maindialog.py:757

```
ows_provider = QgsProviderRegistry.instance().createSelectionWidget(stype[2],
                                                                            self)
        service_type = stype[0]

        # connect dialog signals to iface slots
        if service_type == 'OGC:WMS/OGC:WMTS':
            ows_provider.addRasterLayer.connect(self.iface.addRasterLayer)
```

Open MetaSearch Dialog.
Search for service in csw
Select found wms service
Click on Button AddData
Select WMS/WMTS
Python Error

**QGIS and OS versions**
QGIS 3.10.2 and 3.12.0 on Windows.

With QGIS 3.4 I was able to select WMS/WMTS.  WMS Dialog opens without error.

The API says:
QWidget * QgsProviderRegistry::createSelectionWidget
Deprecated:
QGIS 3.10 - use QgsGui::providerGuiRegistry()->createDataSourceWidget() instead

**Comment by gioman** [comment]
@overkamp is this a regression (worked fine on 3.4?)?

**Comment by gioman** [comment]
I answer myself, is a regression. Does the plugin have an official maintainer?

**Comment by kungzlatan** [comment]
It does work in 3.8 version of qgis on windows if that is any help to track down the issue

**Comment by RickBT** [comment]
Info for users writing PyQGIS Code outside the "QGIS Desktop application" (ex.: coding in a text editor such as Visual Studio Code)

In the "QGIS Desktop application", "iface.activeLayer()" gives access to the currently selected (active) layer in the QGIS-legend. By default there is no legend in a "standalone App", so there is no active layer. Thus, "iface" does not work outside the "QGIS-Desktop environment". (see also this [Link](https://gis.stackexchange.com/questions/164276/why-does-iface-activelayer-not-work-in-a-pyqgis-standalone-app))
