### PR TITLE
QCAMacros.cmake: fix Linux build

### PR DESCRIPTION
**Pull request by rouault**
https://github.com/qgis/QGIS/commit/25ba36180cfbf836b9458beb98e28f62349c4260 causes
build failures on Ubuntu 16.04 and 18.04 with gcc

```
/usr/bin/c++    -I/usr/include/x86_64-linux-gnu/qt5 -I/usr/include/x86_64-linux-gnu/qt5/QtCore -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++-64 -I/usr/include/Qca-qt5/QtCrypto  -fPIE   -std=gnu++11 -o CMakeFiles/cmTC_3b936.dir/qcaossl.cpp.o -c /home/even/qgis/QGIS/build/CMakeFiles/CMakeTmp/qcaossl.cpp
In file included from /usr/include/x86_64-linux-gnu/qt5/QtCore/qchar.h:37:0,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/qstring.h:41,
                 from /usr/include/x86_64-linux-gnu/qt5/QtCore/QString:1,
                 from /usr/include/Qca-qt5/QtCrypto/qca_core.h:36,
                 from /usr/include/Qca-qt5/QtCrypto/qca.h:36,
                 from /usr/include/Qca-qt5/QtCrypto/QtCrypto:1,
                 from /home/even/qgis/QGIS/build/CMakeFiles/CMakeTmp/qcaossl.cpp:2:
/usr/include/x86_64-linux-gnu/qt5/QtCore/qglobal.h:1067:4: error: #error "You must build your code with position independent code if Qt was built with -reduce-relocations. " "Compile your code with -fPIC (-fPIE is not enough)."
 #  error "You must build your code with position independent code if Qt was built with -reduce-relocations. "\
    ^
```

qtglobal.h doesn't like -fPIC and -fPIE together

See https://github.com/qgis/QGIS/pull/6093#issuecomment-393518711

### CODE REVIEW

**Comment by rouault** [comment]
@lbartoletti See above

**Comment by nyalldawson** [comment]
@rouault @lbartoletti @m-kuhn I've reverted 25ba36180cfbf836b9458beb98e28f62349c4260. on master to resurrect the Linux builds temporarily. Let's move discussion for a better fix to this PR.

**Comment by m-kuhn** [comment]
My vote would be merge this and open an issue for CMake.

**Comment by rouault** [comment]
@lbartoletti  I've just re-applied your FreeBSD changes, on top of my fix, since they had been reverted in master in between (fortunately or unfortunately pull requests don't see 'logically conflicting' commits :-) )

**Comment by lbartoletti** [comment]
I've tried with the merge of our patches ;) So it's ok for me. Thanks

**Comment by m-kuhn** [comment]
https://gitlab.kitware.com/cmake/cmake/issues/18056
