### ISSUE TITLE
Rename PostGIS table not working in DB Manager since QGIS 3.10

### ISSUE THREAD

**Issue by FelisPimeja** [qgis/QGIS#32808]
![image](https://user-images.githubusercontent.com/874261/68679728-7d4f1700-0571-11ea-98b5-f3d182efd84d.png)

Trying to rename PostGIS table in DB Manager tree panel with double click or right click -> rename. Getting Python error in console:
```
File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_model.py", line 478, in setData
              obj.rename(new_value)
              File "C:/OSGEO4~1/apps/qgis-dev/./python/plugins\db_manager\db_plugins\plugin.py", line 711, in rename
              ret = self.database().connector.renameTable((self.schemaName(), self.name), new_name)
             AttributeError: 'PostGisDBConnector' object has no attribute 'renameTable'
```
Renaming from Browser panel works fine for me.
No issues in QGIS 3.6.3, 3.8.1, 3.9.0 Win10 x64
Problem occurs in QGIS 3.10 - 3.11 Win10 x64
