### ISSUE TITLE
Error opening data loader dialog from MetaSearch

### ISSUE THREAD

**Issue by AndreasVaage** [qgis/QGIS#40490]
**Describe the bug**

I got the following error when opening the data loader dialog from MetaSearch:

:bangbang: | AttributeError: type object 'WidgetMode' has no attribute 'Embedded' 
:---: | :---

With the full error message:

    Traceback (most recent call last):
    File "/usr/share/qgis/python/plugins/MetaSearch/dialogs/maindialog.py", line 770, in 
    add_to_ows QgsProviderRegistry.WidgetMode.Embedded)
    AttributeError: type object 'WidgetMode' has no attribute 'Embedded'

**How to Reproduce**

1. Open MetaSearch.
2. Select a CSW and a service (I have tested with WMS and WFS).
3. Click "Add Data".
4. Select option from the drop down menu.
5. See error.

**QGIS and OS versions**

QGIS version | 3.16.1-Hannover | QGIS code revision | b381a90dca
-- | -- | -- | --
Compiled against Qt | 5.9.5 | Running against Qt | 5.9.5
Compiled against GDAL/OGR | 2.2.3 | Running against GDAL/OGR | 2.2.3
Compiled against GEOS | 3.6.2-CAPI-1.10.2 | Running against GEOS | 3.6.2-CAPI-1.10.2 4d2925d6
Compiled against SQLite | 3.22.0 | Running against SQLite | 3.22.0
PostgreSQL Client Version | 10.15 (Ubuntu 10.15-0ubuntu0.18.04.1) | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.2
PROJ.4 Version | 493
OS Version | Ubuntu 18.04.5 LTS
Active python plugins | processing; MetaSearch; db_manager

**Additional context**

I first ran into and circumvented issue #38074 by manually upgrading owslib as suggested by  [johtoblans comment](https://github.com/qgis/QGIS/issues/38074#issuecomment-701233465).

The relevant [line](https://github.com/qgis/QGIS/blob/e28ff6f84b99e9b91171184a5cd8080b72c07275/python/plugins/MetaSearch/dialogs/maindialog.py#L770) was introduced in #34861.

**Comment by gioman** [comment]
> **How to Reproduce**
> 
>     1. Open MetaSearch.
> 
>     2. Select a CSW and a service (I have tested with WMS and WFS).
> 
>     3. Click "Add Data".
> 
>     4. Select option from the drop down menu.
> 
>     5. See error.

@AndreasVaage cannot replicate on 3.16.1 on Ubuntu 20.04

**Comment by AndreasVaage** [comment]
Thank you for testing so quickly. I tried purging and installing 3.10.12 LTR instead, but got the same error, except the relevant line changed from 770 to 769. Any suggestion for how I can go forward debugging this?

**Comment by gioman** [comment]
> Any suggestion for how I can go forward debugging this

@tomkralidis any idea?

**Comment by tomkralidis** [comment]
fwiw I cannot reproduce either locally.

**Comment by gioman** [comment]
> fwiw I cannot reproduce either locally.

@tomkralidis I was able to replicate the reported issue on a clean Ubuntu 18.04 machine with QGIS 3.16.1.

I had to upgrade manually owslib to 0.19 (otherwise https://github.com/qgis/QGIS/issues/38074). I was not able to upgrade to a more recent version because it has dependencies (like proj 7.2) that I can't be quickly solved.

**Comment by alexbruy** [comment]
I can't reproduce. Is this still valid?
