### ISSUE TITLE
DB Manager python error on layer preview

### ISSUE THREAD

**Issue by qgib** [qgis/QGIS#29525]
Author Name: **Man Andman** (@Vitruvius21)
Original Redmine Issue: [21709](https://issues.qgis.org/issues/21709)
Affected QGIS version: 3.6.2
Redmine category:db_manager

---
There is a python error when I try to see layer preview in DB Manager. (see attached gif)

*Python error is below ▼*
@WARNING    Traceback (most recent call last):
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\db_manager\db_manager.py", line 119, in tabChanged
              self.refreshTabs()
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\db_manager\db_manager.py", line 142, in refreshTabs
              self.preview.loadPreview(item)
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\db_manager\layer_preview.py", line 62, in loadPreview
              self._clear()
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\db_manager\layer_preview.py", line 89, in _clear
              self._loadTablePreview(None)
              File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins\db_manager\layer_preview.py", line 132, in _loadTablePreview
              self.currentLayerId = vl.id()
             AttributeError: 'NoneType' object has no attribute 'id'@

---

- [123.gif](https://issues.qgis.org/attachments/download/14702/123.gif) (Man Andman)

**Comment by alexbruy** [comment]
Works fine in master and 3.4
