### ISSUE TITLE
Build fails with GCC10 and Qt 5.15.0 with error: invalid use of incomplete type 'class QPainterPath'

### ISSUE THREAD

**Issue by ggardet** [qgis/QGIS#37005]
**Describe the bug**
Build with GCC10 and Qt 5.15.0 fails with ` error: invalid use of incomplete type 'class QPainterPath'`.
Build log:
```
[  889s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp: In function 'void pathArcTo(QPainterPath&, QPointF, qreal, qreal, qreal, int)':
[  889s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:393:7: error: invalid use of incomplete type 'class QPainterPath'
[  889s]   393 |       path.arcTo( circleRect, angle_o / M_PI * 180.0, ( angle_d - angle_o ) / M_PI * 180.0 );
[  889s]       |       ^~~~
[  889s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  889s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  889s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  889s]    54 | class QPainterPath;
[  889s]       |       ^~~~~~~~~~~~
[  889s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:395:7: error: invalid use of incomplete type 'class QPainterPath'
[  889s]   395 |       path.arcTo( circleRect, angle_o / M_PI * 180.0, 360.0 - ( angle_o - angle_d ) / M_PI * 180.0 );
[  889s]       |       ^~~~
[  889s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  889s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  889s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  890s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  890s]    54 | class QPainterPath;
[  890s]       |       ^~~~~~~~~~~~
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:400:7: error: invalid use of incomplete type 'class QPainterPath'
[  890s]   400 |       path.arcTo( circleRect, angle_o / M_PI * 180.0, - ( 360.0 - ( angle_d - angle_o ) / M_PI * 180.0 ) );
[  890s]       |       ^~~~
[  890s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  890s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  890s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  890s]    54 | class QPainterPath;
[  890s]       |       ^~~~~~~~~~~~
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:402:7: error: invalid use of incomplete type 'class QPainterPath'
[  890s]   402 |       path.arcTo( circleRect, angle_o / M_PI * 180.0, ( angle_d - angle_o ) / M_PI * 180.0 );
[  890s]       |       ^~~~
[  890s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  890s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  890s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  890s]    54 | class QPainterPath;
[  890s]       |       ^~~~~~~~~~~~
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp: In function 'void spiralArcTo(QPainterPath&, QPointF, qreal, qreal, qreal, qreal, int)':
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:430:5: error: invalid use of incomplete type 'class QPainterPath'
[  890s]   430 |     path.lineTo( I2 );
[  890s]       |     ^~~~
[  890s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  890s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  890s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  890s]    54 | class QPainterPath;
[  890s]       |       ^~~~~~~~~~~~
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:444:5: error: invalid use of incomplete type 'class QPainterPath'
[  890s]   444 |     path.lineTo( B );
[  890s]       |     ^~~~
[  890s] In file included from /usr/include/qt5/QtGui/qtransform.h:43,
[  890s]                  from /usr/include/qt5/QtGui/QTransform:1,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsmaptopixel.h:22,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/qgsrendercontext.h:29,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbol.h:25,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgssymbollayer.h:30,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.h:21,
[  890s]                  from /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:16:
[  890s] /usr/include/qt5/QtGui/qmatrix.h:54:7: note: forward declaration of 'class QPainterPath'
[  890s]    54 | class QPainterPath;
[  890s]       |       ^~~~~~~~~~~~
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp: In function 'QPolygonF curvedArrow(QPointF, QPointF, QPointF, qreal, qreal, qreal, qreal, QgsArrowSymbolLayer::HeadType, QgsArrowSymbolLayer::ArrowType, qreal)':
[  890s] /home/abuild/rpmbuild/BUILD/qgis-3.12.2/src/core/symbology/qgsarrowsymbollayer.cpp:505:16: error: aggregate 'QPainterPath path' has incomplete type and cannot be defined
[  890s]   505 |   QPainterPath path;
[  890s]       |                ^~~~
```

**How to Reproduce**
Build with GCC10 and Qt 5.15.0.

**QGIS and OS versions**
QGIS 3.12 for openSUSE Tumbleweed

**Additional context**

**Comment by m-kuhn** [comment]
Can you patch the file `src/core/symbology/qgsarrowsymbollayer.cpp` with an additional `#include <QPainterPath>`?
If that helps, it would be great if you could open a pull request.

**Comment by XavierCLL** [comment]
To have a successful build of Qgis 3.12 with Qt5.15 you must apply these patches:

1) https://github.com/qgis/QGIS/commit/31f586ec.patch
2) https://git.archlinux.org/svntogit/community.git/tree/trunk/qgis-pyqt-5.15.patch (from archlinux package)

**Comment by m-kuhn** [comment]
Is this also required for QGIS master? 3.12 is end of life.

**Comment by XavierCLL** [comment]
@m-kuhn I don't sure I didn't test it for master

**Comment by ggardet** [comment]
I confirm that https://github.com/qgis/QGIS/commit/31f586ec.patch fixes the build. 
Thanks!

**Comment by m-kuhn** [comment]
31f586ec comes from this repository and is in master (credits go to @lbartoletti ), it will not be backported to 3.12, because 3.12 is end of life.

Since the affected version 3.12 is EOL I will close this issue.
If there is something left to do for master/3.14 please feel free to reopen.
