### ISSUE TITLE
Execute SQL algorithm can't be added in modeler

### ISSUE THREAD

**Issue by luipir** [qgis/QGIS#36061]
**Describe the bug**
In master a "Execute SQL" can't be added in modeler

**How to Reproduce**

1. Create a new processing model
2. drag&drop Execute SQL algorithm in the modeler canvas => strgger the error in mesageBar

**QGIS and OS versions**

Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] 
QGIS version: 3.13.0-Master Master, 45bead2bb9 

btw going to try with latest pull

works correctly in 3.10

**Additional context**
stacktrace:

An error has occurred while executing Python code: 

AttributeError: 'ModelerParametersDialog' object has no attribute 'widget' 
Traceback (most recent call last):
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerDialog.py", line 314, in addAlgorithm
    dlg = ModelerParametersDialog(alg, self.model())
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 79, in __init__
    self.widget = ModelerParametersWidget(alg, model, algName, configuration, context=self.context, dialog=self)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 500, in __init__
    self.widget = ModelerParametersPanelWidget(alg, model, algName, configuration, dialog, context)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 160, in __init__
    self.setupUi()
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 225, in setupUi
    wrapper = WidgetWrapperFactory.create_wrapper(param, self.dialog)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/gui/wrappers.py", line 1847, in create_wrapper
    return WidgetWrapperFactory.create_wrapper_from_metadata(param, dialog, row, col)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/gui/wrappers.py", line 1882, in create_wrapper_from_metadata
    wrapper = wrapper(param, dialog, row, col, **params)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/gui/wrappers.py", line 155, in __init__
    self.widget = self.createWidget(**kwargs)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/algs/qgis/ui/ExecuteSQLWidget.py", line 139, in createWidget
    return ExecuteSQLWidget(self.dialog)
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/algs/qgis/ui/ExecuteSQLWidget.py", line 57, in __init__
    [QgsProcessingParameterString, QgsProcessingParameterNumber], [])
  File "/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins/processing/modeler/ModelerParametersDialog.py", line 111, in getAvailableValuesOfType
    return self.widget.getAvailableValuesOfType(paramType, outTypes, dataTypes)
AttributeError: 'ModelerParametersDialog' object has no attribute 'widget'

Python version: 3.6.9 (default, Nov  7 2019, 10:44:02) [GCC 8.3.0] 
QGIS version: 3.13.0-Master Master, 45bead2bb9 

Python Path:
/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python
/home/ginetto/.local/share/QGIS/QGIS3/profiles/GaliciaSustentable/python
/home/ginetto/.local/share/QGIS/QGIS3/profiles/GaliciaSustentable/python/plugins
/home/ginetto/PROGRAMMING/QGIS/QGIS-master/build/output/python/plugins
/home/ginetto/.p2/pool/plugins/org.python.pydev.core_6.5.0.201809011628/pysrc
/home/ginetto/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/mnt/data/PROGRAMMING/QGIS/QGIS-master/build/output/python
/home/ginetto
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/home/ginetto/.local/lib/python3.6/site-packages
/usr/local/lib/python3.6/dist-packages
/usr/local/lib/python3.6/dist-packages/tiletanic-0.0.5-py3.6.egg
/usr/local/lib/python3.6/dist-packages/futures-3.2.0-py3.6.egg
/usr/local/lib/python3.6/dist-packages/boto3-1.9.123-py3.6.egg
/usr/local/lib/python3.6/dist-packages/awscli-1.16.133-py3.6.egg
/usr/local/lib/python3.6/dist-packages/geojson-2.4.1-py3.6.egg
/usr/local/lib/python3.6/dist-packages/s3transfer-0.2.0-py3.6.egg
/usr/local/lib/python3.6/dist-packages/jmespath-0.9.4-py3.6.egg
/usr/local/lib/python3.6/dist-packages/botocore-1.12.123-py3.6.egg
/usr/local/lib/python3.6/dist-packages/rsa-3.4.2-py3.6.egg
/usr/local/lib/python3.6/dist-packages/pyasn1-0.4.5-py3.6.egg
/usr/lib/python3/dist-packages
/home/ginetto/.local/share/QGIS/QGIS3/profiles/GaliciaSustentable/python
/home/ginetto/.local/share/QGIS/QGIS3/profiles/GaliciaSustentable/python/plugins/excel_sync/libs/xlwt-1.3.0-py2.py3-none-any.whl
/home/ginetto/.local/share/QGIS/QGIS3/profiles/GaliciaSustentable/python/plugins/excel_sync/libs/xlrd-1.2.0-py2.py3-none-any.whl
/mnt/data/PROGRAMMING/AUTONOMO/GaliciaSustentable/01_ExemploFluxo

**Comment by luipir** [comment]
latest build does not confirm the error
