### ISSUE TITLE
QGis master fails to build with proj 8.0.0 library

### ISSUE THREAD

**Issue by thinkpractice** [qgis/QGIS#42229]
Hi there,

I'm trying to build QGis on Ubuntu 20.04 with ECW support. For this I first build & installed GDAL with ECW support. The version of libproj I've used for GDAL was 8.0.0, which I also compiled from source and installed it in /usr/local/lib (gdal has the same location). After that, I cloned the current QGis master branch and ran the instructions as per [building-on-gnulinux](https://github.com/qgis/QGIS/blob/master/INSTALL.md#3-building-on-gnulinux). Halfway through the build, I get a linker error (see below). The weird thing is that ccmake is finding the correct library & header location. I also removed any other previous installations of libproj. Can anyone enlighten me if it is possible to build QGis with proj 8.0.0?

kind regards,

Tim

 [50%] Linking CXX shared library ../../output/lib/libqgis_core.so
/usr/bin/ld: CMakeFiles/qgis_core.dir/processing/qgsprocessingfeedback.cpp.o: in function `QgsProcessingFeedback::pushVersionInfo(QgsProcessingProvider const*)':
qgsprocessingfeedback.cpp:(.text+0x15c0): undefined reference to `proj_info'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsapplication.cpp.o: in function `QgsApplication::init(QString)':
qgsapplication.cpp:(.text+0x2a1c): undefined reference to `proj_context_set_search_paths'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `getFullProjString(PJconsts*)':
qgscoordinatereferencesystem.cpp:(.text+0xdaf): undefined reference to `proj_crs_create_bound_crs_to_WGS84'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xdfa): undefined reference to `proj_as_proj_string'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xe38): undefined reference to `proj_as_proj_string'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::loadFromDatabase(QString const&, QString const&, QString const&)':
qgscoordinatereferencesystem.cpp:(.text+0x4f75): undefined reference to `proj_create_from_database'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::createFromProj(QString const&, bool)':
qgscoordinatereferencesystem.cpp:(.text+0x6659): undefined reference to `proj_create'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::ellipsoidAcronym() const':
qgscoordinatereferencesystem.cpp:(.text+0x7b3f): undefined reference to `proj_get_ellipsoid'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x7b7e): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x7ba9): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x7c9d): undefined reference to `proj_ellipsoid_get_parameters'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::bounds() const':
qgscoordinatereferencesystem.cpp:(.text+0x8197): undefined reference to `proj_get_area_of_use'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::setProjString(QString const&)':
qgscoordinatereferencesystem.cpp:(.text+0x83ed): undefined reference to `proj_create'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::setWktString(QString const&)':
qgscoordinatereferencesystem.cpp:(.text+0x85e4): undefined reference to `proj_create_from_wkt'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x8692): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x869e): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x8771): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x87a7): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x891f): undefined reference to `proj_get_name'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::setMapUnits()':
qgscoordinatereferencesystem.cpp:(.text+0x8b58): undefined reference to `proj_crs_get_coordinate_system'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x8bc2): undefined reference to `proj_cs_get_axis_count'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x8c25): undefined reference to `proj_cs_get_axis_info'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::toWkt(QgsCoordinateReferenceSystem::WktVariant, bool, int) const':
qgscoordinatereferencesystem.cpp:(.text+0x9faf): undefined reference to `proj_as_wkt'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `testIsGeographic(PJconsts*)':
qgscoordinatereferencesystem.cpp:(.text+0xd2ca): undefined reference to `proj_crs_get_coordinate_system'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xd30e): undefined reference to `proj_cs_get_axis_count'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xd36a): undefined reference to `proj_cs_get_axis_info'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xd3b6): undefined reference to `proj_uom_get_info_from_database'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::loadFromAuthCode(QString const&, QString const&)':
qgscoordinatereferencesystem.cpp:(.text+0xda48): undefined reference to `proj_create_from_database'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xdaac): undefined reference to `proj_get_type'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xdc01): undefined reference to `proj_get_name'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::matchToUserCrs() const':
qgscoordinatereferencesystem.cpp:(.text+0xe600): undefined reference to `proj_is_equivalent_to'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::syncDatabase()':
qgscoordinatereferencesystem.cpp:(.text+0xedfa): undefined reference to `proj_get_authorities_from_database'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xee6b): undefined reference to `proj_get_codes_from_database'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xef1d): undefined reference to `proj_create_from_database'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xef69): undefined reference to `proj_get_type'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xf0b5): undefined reference to `proj_is_deprecated'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0xf0d7): undefined reference to `proj_get_name'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x10267): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x10423): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystem::geographicCrsAuthId() const':
qgscoordinatereferencesystem.cpp:(.text+0x10eb4): undefined reference to `proj_crs_get_geodetic_crs'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x10f1c): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text+0x10f4d): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystemPrivate::cleanPjObjects()':
qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv[_ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv]+0x20): undefined reference to `proj_context_create'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv[_ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv]+0x81): undefined reference to `proj_assign_context'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv[_ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv]+0x98): undefined reference to `proj_destroy'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv[_ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv]+0xec): undefined reference to `proj_assign_context'
/usr/bin/ld: qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv[_ZN35QgsCoordinateReferenceSystemPrivate14cleanPjObjectsEv]+0x10d): undefined reference to `proj_context_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystemPrivate::threadLocalProjObject() const':
qgscoordinatereferencesystem.cpp:(.text._ZNK35QgsCoordinateReferenceSystemPrivate21threadLocalProjObjectEv[_ZNK35QgsCoordinateReferenceSystemPrivate21threadLocalProjObjectEv]+0xec): undefined reference to `proj_clone'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatereferencesystem.cpp.o: in function `QgsCoordinateReferenceSystemPrivate::removeObjectsBelongingToCurrentThread(pj_ctx*)':
qgscoordinatereferencesystem.cpp:(.text._ZN35QgsCoordinateReferenceSystemPrivate37removeObjectsBelongingToCurrentThreadEP6pj_ctx[_ZN35QgsCoordinateReferenceSystemPrivate37removeObjectsBelongingToCurrentThreadEP6pj_ctx]+0x99): undefined reference to `proj_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatetransform.cpp.o: in function `QgsCoordinateTransform::transformCoords(int, double*, double*, double*, QgsCoordinateTransform::TransformDirection) const':
qgscoordinatetransform.cpp:(.text+0x2b4a): undefined reference to `proj_errno_reset'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x2bef): undefined reference to `proj_trans_generic'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x2c15): undefined reference to `proj_errno'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x2c38): undefined reference to `proj_errno'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x2db6): undefined reference to `proj_errno_reset'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x2e3f): undefined reference to `proj_trans_generic'
/usr/bin/ld: qgscoordinatetransform.cpp:(.text+0x344c): undefined reference to `proj_errno_string'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatetransform_p.cpp.o: in function `QgsCoordinateTransformPrivate::threadLocalProjData()':
qgscoordinatetransform_p.cpp:(.text+0xc68): undefined reference to `proj_create'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0xcc6): undefined reference to `proj_coordoperation_is_instantiable'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0xf85): undefined reference to `proj_create_operation_factory_context'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0xfaa): undefined reference to `proj_operation_factory_context_set_grid_availability_use'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0xfc8): undefined reference to `proj_operation_factory_context_set_spatial_criterion'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1010): undefined reference to `proj_create_operations'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1034): undefined reference to `proj_list_get_count'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x105f): undefined reference to `proj_context_errno'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1084): undefined reference to `proj_errno_string'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1144): undefined reference to `proj_list_get'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1194): undefined reference to `proj_coordoperation_is_instantiable'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x11cf): undefined reference to `proj_coordoperation_get_grid_used_count'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1289): undefined reference to `proj_coordoperation_get_grid_used'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1597): undefined reference to `proj_normalize_for_visualization'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x171f): undefined reference to `proj_list_get'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x176b): undefined reference to `proj_coordoperation_is_instantiable'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1a69): undefined reference to `proj_normalize_for_visualization'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1bae): undefined reference to `proj_list_destroy'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1bbd): undefined reference to `proj_operation_factory_context_destroy'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1c09): undefined reference to `proj_context_errno'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x1c2e): undefined reference to `proj_errno_string'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatetransform_p.cpp.o: in function `QgsCoordinateTransformPrivate::threadLocalFallbackProjData()':
qgscoordinatetransform_p.cpp:(.text+0x248a): undefined reference to `proj_create_crs_to_crs_from_pj'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x24cb): undefined reference to `proj_normalize_for_visualization'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatetransform_p.cpp.o: in function `QgsCoordinateTransformPrivate::freeProj()':
qgscoordinatetransform_p.cpp:(.text+0x26af): undefined reference to `proj_context_create'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x26fc): undefined reference to `proj_assign_context'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x2713): undefined reference to `proj_destroy'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x277e): undefined reference to `proj_assign_context'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x2795): undefined reference to `proj_destroy'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x27af): undefined reference to `proj_context_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgscoordinatetransform_p.cpp.o: in function `QgsCoordinateTransformPrivate::removeObjectsBelongingToCurrentThread(void*)':
qgscoordinatetransform_p.cpp:(.text+0x28c3): undefined reference to `proj_destroy'
/usr/bin/ld: qgscoordinatetransform_p.cpp:(.text+0x293f): undefined reference to `proj_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdatumtransform.cpp.o: in function `QgsDatumTransform::operations(QgsCoordinateReferenceSystem const&, QgsCoordinateReferenceSystem const&, bool)':
qgsdatumtransform.cpp:(.text+0xa3): undefined reference to `proj_create_operation_factory_context'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0xc8): undefined reference to `proj_operation_factory_context_set_grid_availability_use'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0xe6): undefined reference to `proj_operation_factory_context_set_spatial_criterion'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x10d): undefined reference to `proj_operation_factory_context_set_discard_superseded'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x14d): undefined reference to `proj_create_operations'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x171): undefined reference to `proj_list_get_count'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x1b2): undefined reference to `proj_list_get'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x278): undefined reference to `proj_list_destroy'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x287): undefined reference to `proj_operation_factory_context_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdatumtransform.cpp.o: in function `QgsDatumTransform::transformDetailsFromPj(PJconsts*)':
qgsdatumtransform.cpp:(.text+0x2b21): undefined reference to `proj_normalize_for_visualization'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2b71): undefined reference to `proj_as_proj_string'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2bde): undefined reference to `proj_as_proj_string'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2c41): undefined reference to `proj_get_name'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2c98): undefined reference to `proj_coordoperation_get_accuracy'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2cbe): undefined reference to `proj_coordoperation_is_instantiable'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2ce1): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2d36): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2ded): undefined reference to `proj_get_area_of_use'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2ece): undefined reference to `proj_get_remarks'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2f1e): undefined reference to `proj_get_scope'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2f76): undefined reference to `proj_coordoperation_get_grid_used_count'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x2ff5): undefined reference to `proj_coordoperation_get_grid_used'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x315f): undefined reference to `proj_get_type'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x318d): undefined reference to `proj_concatoperation_get_step_count'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x31ba): undefined reference to `proj_concatoperation_get_step'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3200): undefined reference to `proj_get_remarks'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3252): undefined reference to `proj_get_scope'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x32a5): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x32fc): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3373): undefined reference to `proj_get_area_of_use'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x340f): undefined reference to `proj_get_remarks'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3453): undefined reference to `proj_get_scope'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3498): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x34e1): undefined reference to `proj_get_id_code'
/usr/bin/ld: qgsdatumtransform.cpp:(.text+0x3550): undefined reference to `proj_get_area_of_use'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::measureLine(QVector<QgsPointXY> const&) const':
qgsdistancearea.cpp:(.text+0x11f5): undefined reference to `geod_inverse'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::measureLine(QgsPointXY const&, QgsPointXY const&) const':
qgsdistancearea.cpp:(.text+0x1593): undefined reference to `geod_inverse'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::computeSpheroidProject(QgsPointXY const&, double, double) const':
qgsdistancearea.cpp:(.text+0x1a9b): undefined reference to `geod_direct'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::latitudeGeodesicCrossesAntimeridian(QgsPointXY const&, QgsPointXY const&, double&) const':
qgsdistancearea.cpp:(.text+0x1ec0): undefined reference to `geod_inverseline'
/usr/bin/ld: qgsdistancearea.cpp:(.text+0x2022): undefined reference to `geod_inverseline'
/usr/bin/ld: qgsdistancearea.cpp:(.text+0x20a8): undefined reference to `geod_position'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::geodesicLine(QgsPointXY const&, QgsPointXY const&, double, bool) const':
qgsdistancearea.cpp:(.text+0x30ca): undefined reference to `geod_inverseline'
/usr/bin/ld: qgsdistancearea.cpp:(.text+0x3209): undefined reference to `geod_position'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::bearing(QgsPointXY const&, QgsPointXY const&) const':
qgsdistancearea.cpp:(.text+0x4101): undefined reference to `geod_inverse'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::computeAreaInit() const':
qgsdistancearea.cpp:(.text+0x42a7): undefined reference to `geod_init'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsdistancearea.cpp.o: in function `QgsDistanceArea::computePolygonArea(QVector<QgsPointXY> const&) const':
qgsdistancearea.cpp:(.text+0x4437): undefined reference to `geod_polygon_init'
/usr/bin/ld: qgsdistancearea.cpp:(.text+0x454c): undefined reference to `geod_polygon_addpoint'
/usr/bin/ld: qgsdistancearea.cpp:(.text+0x459d): undefined reference to `geod_polygon_compute'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsellipsoidutils.cpp.o: in function `QgsEllipsoidUtils::definitions()':
qgsellipsoidutils.cpp:(.text+0x2026): undefined reference to `proj_get_authorities_from_database'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x2088): undefined reference to `proj_get_codes_from_database'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x20f8): undefined reference to `proj_create_from_database'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x214d): undefined reference to `proj_get_name'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x2389): undefined reference to `proj_ellipsoid_get_parameters'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x27b6): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: qgsellipsoidutils.cpp:(.text+0x27d2): undefined reference to `proj_string_list_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjContext::QgsProjContext()':
qgsprojutils.cpp:(.text+0x1c): undefined reference to `proj_context_create'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjContext::~QgsProjContext()':
qgsprojutils.cpp:(.text+0x63): undefined reference to `proj_context_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::ProjPJDeleter::operator()(PJconsts*)':
qgsprojutils.cpp:(.text+0x98): undefined reference to `proj_destroy'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::usesAngularUnit(QString const&)':
qgsprojutils.cpp:(.text+0x1bf): undefined reference to `proj_create'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x218): undefined reference to `proj_crs_get_coordinate_system'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x265): undefined reference to `proj_cs_get_axis_count'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x2c1): undefined reference to `proj_cs_get_axis_info'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x30d): undefined reference to `proj_uom_get_info_from_database'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::axisOrderIsSwapped(PJconsts const*)':
qgsprojutils.cpp:(.text+0x47b): undefined reference to `proj_crs_get_coordinate_system'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x4c8): undefined reference to `proj_cs_get_axis_count'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x517): undefined reference to `proj_cs_get_axis_info'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::crsToSingleCrs(PJconsts const*)':
qgsprojutils.cpp:(.text+0x610): undefined reference to `proj_get_type'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x631): undefined reference to `proj_get_source_crs'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x665): undefined reference to `proj_crs_get_sub_crs'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x69b): undefined reference to `proj_get_type'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x6b4): undefined reference to `proj_get_type'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x6e3): undefined reference to `proj_crs_get_sub_crs'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x72b): undefined reference to `proj_clone'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::identifyCrs(PJconsts const*, QString&, QString&, QFlags<QgsProjUtils::IdentifyFlag>)':
qgsprojutils.cpp:(.text+0x809): undefined reference to `proj_identify'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x824): undefined reference to `proj_list_get_count'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x87f): undefined reference to `proj_list_get'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x8a5): undefined reference to `proj_get_type'
/usr/bin/ld: qgsprojutils.cpp:(.text+0x93a): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgsprojutils.cpp:(.text+0xa21): undefined reference to `proj_list_destroy'
/usr/bin/ld: qgsprojutils.cpp:(.text+0xa2d): undefined reference to `proj_int_list_destroy'
/usr/bin/ld: qgsprojutils.cpp:(.text+0xa70): undefined reference to `proj_get_id_auth_name'
/usr/bin/ld: qgsprojutils.cpp:(.text+0xaba): undefined reference to `proj_get_id_code'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::coordinateOperationIsAvailable(QString const&)':
qgsprojutils.cpp:(.text+0xbf8): undefined reference to `proj_create'
/usr/bin/ld: qgsprojutils.cpp:(.text+0xc4e): undefined reference to `proj_coordoperation_is_instantiable'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::gridsUsed(QString const&)':
qgsprojutils.cpp:(.text+0xf5e): undefined reference to `proj_grid_get_info_from_database'
/usr/bin/ld: CMakeFiles/qgis_core.dir/qgsprojutils.cpp.o: in function `QgsProjUtils::searchPaths()':
qgsprojutils.cpp:(.text+0x11aa): undefined reference to `proj_info'
collect2: error: ld returned 1 exit status
make[2]: *** [src/core/CMakeFiles/qgis_core.dir/build.make:12393: output/lib/libqgis_core.so.3.19.0] Error 1
make[1]: *** [CMakeFiles/Makefile2:4276: src/core/CMakeFiles/qgis_core.dir/all] Error 2
make: *** [Makefile:163: all] Error 2

**Comment by nyalldawson** [comment]
It's not related to proj 8 - qgis will compile correctly with that version. This is a local build configuration issue only - you'll need to double check your setup and cmake configuration.

**Comment by thinkpractice** [comment]
For anyone running into the same problem, look [here](http://osgeo-org.1560.x6.nabble.com/QGIS-Developer-Trying-to-build-with-GDAL3-PROJ6-anybody-successful-td5405185.html)

compiling with: -DCMAKE_CXX_FLAGS=-DPROJ_RENAME_SYMBOLS seemed to fix the problem.
