### ISSUE TITLE
MetaSearch unexpected keyword argument 'auth'

### ISSUE THREAD

**Issue by ahayes** [qgis/QGIS#38074]
**Describe the bug**

Receiving error `Unknown Error: __init__() got an unexpected keyword argument 'auth'` when attempting to search a CSW endpoint. Web -> MetaSearch -> MetaSearch core plugin.

**How to Reproduce**

QGIS version | 3.14.1-Pi | QGIS code revision | de08d6b71d
-- | -- | -- | --
Compiled against Qt | 5.12.3 | Running against Qt | 5.12.3
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.2 | Running against GEOS | 3.7.2-CAPI-1.11.2 b55d2125
Compiled against SQLite | 3.28.0 | Running against SQLite | 3.28.0
PostgreSQL Client Version | 11.3 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.4 | QScintilla2 Version | 2.11.1
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | macOS Mojave (10.14)
Active python plugins | processing; db_manager; MetaSearch

**Additional context**

 This was working in QGIS 3.8 immediately before upgrading and isn't working after upgrading to 3.14.1. I have tried deleting and recreating the service entry in the MetaSearch `Services` tab. I have tried with a fresh QGIS user profile. I am pointing at a recently deployed and tested pyCSW endpoint. I have tried another endpoint that I believe to be good (http://onegeology-geonetwork.brgm.fr/geonetwork3/srv/eng/csw) with the same result.

**Comment by NyakudyaA** [comment]
Ping @Samweli

**Comment by gioman** [comment]
> Ping @Samweli

also @tomkralidis Confirmed also on master. It seems ok on 3.10.

**Comment by tomkralidis** [comment]
cc @jef-n 

Confirmed.  The QGIS build (3.14 && master) shows OWSLib 0.17.1, but requires OWSLib 0.20.0.  In QGIS Python console:
```python
import owslib
owslib
<module 'owslib' from '/Applications/QGIS3.14.app/Contents/MacOS/../Resources/python/owslib/__init__.py'>
owslib.__version__
'0.17.1'
```

**Comment by PeterPetrik** [comment]
Are you sure it needs 0.20.0? In current build https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20200924_035824.dmg we have owslib 0.19.2, and I am unable to replicate the issue. 

I was able to search successfully without error?
![Uploading Screenshot 2020-09-24 at 15.59.40.png…]()

**Comment by johtoblan** [comment]
Had same problem with fresh install from https://qgis.org/en/site/forusers/alldownloads.html#debian-ubuntu on Ubuntu 18.

```python3
import owslib
owslib
<module 'owslib' from '/usr/lib/python3/dist-packages/owslib/__init__.py'>
owslib.__version__
'0.16.0'
```

Fixed with manual pip3 installation of owslib to override.

**Comment by meridsa** [comment]
@johtoblan Could you explain the steps taken to manually upgrade owslib with pip3?

**Comment by albertograva** [comment]
I have the same errore on 3.16.3 with ubuntu 18.04

**Comment by GisUsers** [comment]
Installed QGIS 3.18.1 on Debian buster from official repo. OWSLib is 0.17.1 and still receiving the error when attempting to search a CSW.
