### PR TITLE
untwine pdalprovider integration

### PR DESCRIPTION
**Pull request by PeterPetrik**
- Ability to generate EPT index for (smaller) laz files directly in QGIS via https://github.com/hobu/untwine library

https://twitter.com/lutraconsulting/status/1334173708542480398

### CODE REVIEW

**Comment by nyalldawson** [comment]
> index for (smaller) laz files 

is the "smaller" qualification here because you currently do this in the main thread? or an inherent limitation in untwine?

**Comment by PeterPetrik** [comment]
> > index for (smaller) laz files
> 
> is the "smaller" qualification here because you currently do this in the main thread? or an inherent limitation in untwine?

we need to pick some limit number where we say, sorry, index it from the console (because you may just need cloud to index it in some reasonable time.) With one file it is ok, but you are able to index the whole folder, where it can be tricky. 

we will move it to background thread in this PR

**Comment by nirvn** [comment]
What about having a processing alg too?

**Comment by PeterPetrik** [comment]
that could be added of course.

**Comment by nirvn** [comment]
That's be great, and it'd be friendlier to direct users to a processing alg instead of a CLI :)

**Comment by PeterPetrik** [comment]
laz_qgis2

File: src/core/providers/ept/qgseptprovider.h [hunk 1]
```diff
@@ -47,15 +48,22 @@ class QgsEptProvider: public QgsPointCloudDataProvider
...
 
+  private slots:
+    void onLoadIndexFinished();
+
   private:
-    std::unique_ptr<QgsEptPointCloudIndex> mIndex;
+    void loadIndex();
+
+    QString mUri;
+    QSharedPointer<QgsEptPointCloudIndex> mIndex;
```
Comment (nyalldawson) [inline src/core/providers/ept/qgseptprovider.h]: Can we remove the shared pointer here and just directly take ownership of it?

File: src/core/providers/ept/qgseptprovider.cpp [hunk 2]
```diff
@@ -73,29 +86,66 @@ QString QgsEptProvider::description() const
...
+  QgsApplication::taskManager()->addTask( task );
+}
+
+void QgsEptProvider::onLoadIndexFinished()
+{
+  QgsEptPointCloudIndexLoadingTask *task = qobject_cast<QgsEptPointCloudIndexLoadingTask *>( QObject::sender() );
+  // this may be already canceled task that we don't care anymore...
+  if ( task == mRunningIndexingTask )
+  {
+    mIndex = mRunningIndexingTask->index();
```
Comment (nyalldawson) [inline src/core/providers/ept/qgseptprovider.cpp:133]: This should probably be something like "takeIndex" which transfers ownership

Comment (nyalldawson) [reply src/core/providers/ept/qgseptprovider.cpp:133]: That said - QgsPointCloudIndex is currently a qobject, so we have to be careful moving it between threads. I can't see any reason it HAS to be a qobject though, so I suggest we just remove that...

**Comment by nyalldawson** [comment]
@PeterPetrik one thing we'll need to consider is how to avoid trying to build an index for the same las file on two different threads. E.g. if a user loads the same layer again while an index is being built, or in future if a processing algorithm running on a background thread loads a layer then we potentially will have two tasks trying to create an ept file in the same location.

We maybe need some index creation pool where the data provider can request index creation for a file from, and that would return a "index already building" state if another thread asks for the same index (or a link to the generated ept file if another thread has just finished building the index in the time between a data provider checking for an existing one and the task being created to build one...)

**Comment by wonder-sk** [comment]
> one thing we'll need to consider is how to avoid trying to build an index for the same las file on two different threads. E.g. if a user loads the same layer again while an index is being built, or in future if a processing algorithm running on a background thread loads a layer then we potentially will have two tasks trying to create an ept file in the same location.

How about we would avoid it with just simple logic upon layer load:
- if the directory with index is missing -> start creating index
- if the directory with index is there
  - if "temp" sub-directory is there -> someone is building index, let's wait until it is ready
  - if "temp" sub-directory is not there -> index is ready, let's use it

This should hopefully work even if some other QGIS instance is building that index...?

File: src/core/providers/ept/qgseptprovider.cpp (hunk 2 above)
Comment (PeterPetrik) [reply src/core/providers/ept/qgseptprovider.cpp]: ok, talked with Martin and the ept load will be in main thread for now (should be quick from files)

**Comment by PeterPetrik** [comment]
> How about we would avoid it with just simple logic upon layer load:

did something along the lines in the implementation. I prefer just say sorry, when there is "temp" folder present, since it could be for example crashed previous run, so you can wait forever?

**Comment by PeterPetrik** [comment]
this is not ready for review.

- only I do not know if the default should be to skip or not-skip the auto-generation of EPT index

File: src/core/pointcloud/qgspointcloudlayer.cpp [hunk 3]
```diff
@@ -341,12 +361,30 @@ void QgsPointCloudLayer::setDataSource( const QString &dataSource, const QString
...
   triggerRepaint();
 }
 
+void QgsPointCloudLayer::onPointCloudIndexLoaded()
+{
+  if ( mRenderer )
+  {
+    // Renderer is already set only in case
+    // we generated the point cloud index
+    // as a background job. In this case
```
Comment (wonder-sk) [inline src/core/pointcloud/qgspointcloudlayer.cpp:374]: Having this logic based on mRenderer seems a bit fragile to me...

Loading of a point cloud index should be a fairly fast synchronous operation, where we don't need to emit signals... I would suggest to maybe instead have 1. enumeration with states: { not indexed, indexing, indexed }, and 2. signal to tell change of the state. This would have hopefully give better feedback also to other bits of the qgis environment - for example, layer tree panel could show indicators for the point cloud layers that are being indexed (or waiting in queue to be indexed). If we had a setting to disable auto-indexing of point cloud layers, then users could maybe even click these indicators to actually start indexing...

Now going a bit off-topic - it would be good to probably limit number of layers that get simultaneously indexed to max. 1 (at least initially) - indexing may take multiple threads and drag'n'drop of several point cloud files may make the computer unresponsive (and/or more likely to run out of memory).

File: src/providers/pdal/CMakeLists.txt [hunk 4]
```diff
@@ -53,11 +110,35 @@ include_directories(SYSTEM
...
 )
 
-add_library (pdalprovider MODULE ${PDAL_SRCS} ${PDAL_HDRS})
+add_executable(untwine ${UNTWINE_SRCS} ${UNTWINE_HDRS})
+set_target_properties(untwine PROPERTIES
+  RUNTIME_OUTPUT_DIRECTORY ${QGIS_OUTPUT_DIRECTORY}/${QGIS_LIBEXEC_SUBDIR}
+)
+
+target_link_libraries (untwine
+  ${PDAL_LIBRARIES}
```
Comment (wonder-sk) [inline src/providers/pdal/CMakeLists.txt:119]: I had to add `pthread` on linux to get untwine compiled (travis does not complain because it does not build PDAL provider I guess?)

File: src/providers/pdal/qgspdaleptgenerationtask.cpp [hunk 5]
```diff
@@ -0,0 +1,181 @@
...
+
+  return true;
+}
+
+void QgsPdalEptGenerationTask::cleanTemp()
+{
+  QDir tmpDir( mOutputDir + QStringLiteral( "/temp" ) );
+  if ( tmpDir.exists() )
+  {
+    QgsMessageLog::logMessage( tr( "Removing temporary files in %1" ).arg( tmpDir.dirName() ), QObject::tr( "Untwine" ), Qgis::Info );
```
Comment (wonder-sk) [inline src/providers/pdal/qgspdaleptgenerationtask.cpp:60]: Instead of using `QObject::tr( "Untwine" )` for the category I would use non-translatable string (it's a project name) or maybe even better, translatable string e.g. "Point clouds"

File: src/providers/pdal/qgspdaleptgenerationtask.cpp [hunk 6]
```diff
@@ -0,0 +1,181 @@
...
+  }
+  else
+  {
+    QgsMessageLog::logMessage( tr( "Using executable %1" ).arg( mUntwineExecutableBinary ), QObject::tr( "Untwine" ), Qgis::Info );
+  }
+
+  untwine::QgisUntwine untwineProcess( mUntwineExecutableBinary.toStdString() );
+
+  std::vector<std::string> files = {mFile.toStdString()};
+  untwineProcess.start( files, mOutputDir.toStdString() );
```
Comment (wonder-sk) [inline src/providers/pdal/qgspdaleptgenerationtask.cpp:81]: Could you please check if this works also with non-unicode paths (both input file and untwine exe path) ?

File: src/providers/pdal/qgspdalprovider.cpp [hunk 7]
```diff
@@ -58,8 +61,82 @@ QgsRectangle QgsPdalProvider::extent() const
...
+QVariant QgsPdalProvider::metadataClassStatistic( const QString &attribute, const QVariant &value, QgsStatisticalSummary::Statistic statistic ) const
+{
+  return mIndex->metadataClassStatistic( attribute, value, statistic );
+}
+
+
+
+void QgsPdalProvider::loadIndex( bool skipIndexGeneration )
+{
+  if ( !mIsValid )
```
Comment (wonder-sk) [inline src/providers/pdal/qgspdalprovider.cpp:81]: Is this condition correct? Because of this condition, indexing was not starting for me at all... When I changed it, then it started to run untwine...
```suggestion
  if ( mIsValid )
```

**Review by wonder-sk — COMMENTED** [review]
What happens if untwine process gets killed or crashes - are we going to detect it?

When indexing started, I got this reported on console and nothing got built - assuming untwine crashed:
```
terminate called after throwing an instance of 'char const*'
```

File: src/providers/pdal/qgspdalprovider.cpp (hunk 7 above)
Comment (wonder-sk) [reply src/providers/pdal/qgspdalprovider.cpp:81]: Hmm and now when I have `if ( mIsValid )` it re-indexes my files every time :-)

File: src/providers/pdal/qgspdaleptgenerationtask.cpp [hunk 8]
```diff
@@ -0,0 +1,181 @@
...
+  {
+    QThread::msleep( 100 );
+    int percent = untwineProcess.progressPercent();
+    if ( lastPercent != percent )
+    {
+      QString message = QString::fromStdString( untwineProcess.progressMessage() );
+      if ( !message.isEmpty() )
+        QgsMessageLog::logMessage( message, QObject::tr( "Untwine" ), Qgis::Info );
+
+      setProgress( percent / 100.0 );
```
Comment (wonder-sk) [inline src/providers/pdal/qgspdaleptgenerationtask.cpp:93]: I think untwine reports values 0-100 so there's no need to divide it by 100.0 - `setProgress()` expects values 0-100 ... that would also explain why the progress bar behaved strangely

File: src/providers/pdal/qgspdaleptgenerationtask.cpp (hunk 6 above)
Comment (PeterPetrik) [reply src/providers/pdal/qgspdaleptgenerationtask.cpp:81]: added non-ascii testcase

**Comment by PeterPetrik** [comment]
@wonder-sk ready for rereview

**Review by wonder-sk — COMMENTED** [review]
Thanks for the updates!

Two things that come to my mind:
- currently it is not possible to find out provider's index generation state - we only get signals about state change
- if I understand correctly - if an index is already being generated, newly added layers won't get their index created at all. This behavior would make things difficult for people if they would drag'n'drop e.g. 5 files, but only one gets indexed. I thought we would create tasks for all those layers, but maybe just not run them all at once to avoid killing the machine... Not sure if the task manager has some functionality to e.g. only allow one task of a kind to be run at a time? Or maybe we can simply have a primitive mechanism, where pdal provider would run a timer (e.g. with 1 second interval) which would periodically check if there are no other tasks running and if not, then it would schedule index generation?

**Comment by PeterPetrik** [comment]
I agree with possiblity to restart job for user, but I would defer it to the consequent PRs. Not sure if I like timer for this, maybe some kind of infrastructure in qgstaskmanage to queue jobs with the same type would be best.

**Review by wonder-sk — APPROVED** [review]
LGTM! And yeah let's get this merged and handle the case with multiple layers on a separate pull request.

**Comment by nirvn** [comment]
FYI,  untwine seems to require pdal 2.2 otherwise it fails to compile:

```
In file included from /home/webmaster/dev/cpp/QGIS/external/untwine/bu/BuPyramid.hpp:20,
                 from /home/webmaster/dev/cpp/QGIS/external/untwine/bu/BuPyramid.cpp:9:
/home/webmaster/dev/cpp/QGIS/external/untwine/bu/PyramidManager.hpp:20:10: fatal error: pdal/util/ThreadPool.hpp: No such file or directory
   20 | #include <pdal/util/ThreadPool.hpp>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

**Comment by nirvn** [comment]
@PeterPetrik , good news, PDAL is really to self-build.

That said, I had to add the following line to src/providers/pdal/CMakeLists.txt to successfully build on Ubuntu 20.20:

`SET(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -pthread")`

Without it, I get the following error when building the pdal provider:

`undefined reference to symbol 'pthread_create@@GLIBC_2.2.5'`

**Comment by jef-n** [comment]
> FYI, untwine seems to require pdal 2.2 otherwise it fails to compile:

See also https://cdash.orfeo-toolbox.org/index.php?project=QGIS&date=2020-12-15 (ie. breaks nightlies for ubuntu bionic, focal, groovy and debian buster).

**Comment by wonder-sk** [comment]
Will have a look at the issues and create a PR to fix them...

**Comment by wonder-sk** [comment]
@jef-n looking into cmakelists, PDAL provider is off by default, so the debian/ubuntu builds must be explicitly configured with PDAL turned on, right? I think for the time being we will need to turn off PDAL provider on debian/ubuntu as we require PDAL 2.2 at this point. Will check with Hobu how difficult it would be to lower this minimum version requirement - I guess it would be nice if we could run with PDAL 2.0.1 which is available on Ubuntu 20.04 LTS...

File: tests/src/providers/testqgspdalprovider.cpp [hunk 9]
```diff
@@ -174,6 +189,27 @@ void TestQgsPdalProvider::validLayer()
...
+  QVERIFY( task.run() );
+  QFileInfo fi( dir.path() + "/ept.json" );
+  QVERIFY( fi.exists() );
+}
+
+void TestQgsPdalProvider::testEptGenerationNonASCII()
+{
+  QTemporaryDir dir;
+  QVERIFY( dir.isValid() );
+  QgsPdalEptGenerationTask task( mTestDataDir + QStringLiteral( "point_clouds/las/cloud%!* _*čopy.las" ), dir.path() );
```
Comment (roya0045) [inline tests/src/providers/testqgspdalprovider.cpp:209]: Why was this a good filename? This literally breaks git on windows and prevent changing branch. Renaming this would solve the issue.
