### ISSUE TITLE
Python was broken after upgrade from 3.14 to 3.16

### ISSUE THREAD

**Issue by sk-dataocean-online** [qgis/QGIS#39990]
I had no problems with version 3.14 Pi but after upgrade to 3.16 the app throws errors on loading installed plugins (the same error for each plugin at startup):

```
ImportError: cannot import name 'QgsCodeEditorPython' from 'qgis.gui' (/app/share/qgis/python/qgis/gui/__init__.py)

Python version: 3.8.6 (default, Nov 10 2011, 15:00:00) [GCC 10.2.0] 
QGIS version: 3.16.0-Hannover Hannover, 43b64b13 

Python Path:
/app/share/qgis/python
/home/stanislav/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/stanislav/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins
/app/share/qgis/python/plugins
/usr/lib/python38.zip
/usr/lib/python3.8
/usr/lib/python3.8/lib-dynload
/usr/lib/python3.8/site-packages
/app/lib/python3.8/site-packages
/app/lib/python3.8/site-packages/numpy-1.19.2-py3.8-linux-x86_64.egg
/app/lib/python3.8/site-packages/MarkupSafe-1.1.1-py3.8-linux-x86_64.egg
/home/stanislav/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python
/home/stanislav/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools/tools
/home/stanislav/.var/app/org.qgis.qgis/data/QGIS/QGIS3/profiles/default/python/plugins/DigitizingTools
```

Attempt to invoke python console throws the same error.

OS: Linux Mint 18.3 (based on Ubuntu 16.04)
I don't have python 3.8 installed:
```
stanislav@stanislav-TM1703 ~ $ sudo update-alternatives --config python
There are 3 choices for the alternative python (providing /usr/bin/python).

  Selection    Path                      Priority   Status
------------------------------------------------------------
* 0            /usr/local/bin/python3.7   3         auto mode
  1            /usr/bin/python2.7         1         manual mode
  2            /usr/bin/python3.5         2         manual mode
  3            /usr/local/bin/python3.7   3         manual mode
```

**Comment by nyalldawson** [comment]
You're missing a required dependancy -- the QScintilla python library

**Comment by sk-dataocean-online** [comment]
> You're missing a required dependancy -- the QScintilla python library

How could I install that into QGIS's python? "pip3 install QScintilla" installs it into system's python. What I am missing?
BTW I didn't compile QGIS but rather downloaded it as an available flatpak version from OS standard repository.

**Comment by sk-dataocean-online** [comment]
It seems that QScintilla is installed:

QGIS version | 3.16.0-Hannover | QGIS code revision | 43b64b13
-- | -- | -- | --
Compiled against Qt | 5.15.1 | Running against Qt | 5.15.1
Compiled against GDAL/OGR | 3.0.4 | Running against GDAL/OGR | 3.0.4
Compiled against GEOS | 3.8.1-CAPI-1.13.3 | Running against GEOS | 3.8.1-CAPI-1.13.3
Compiled against SQLite | 3.32.1 | Running against SQLite | 3.32.1
PostgreSQL Client Version | 12.2 | SpatiaLite Version | 4.3.0a
QWT Version | 6.1.5 | QScintilla2 Version | 2.11.5
Compiled against PROJ | 6.3.2 | Running against PROJ | Rel. 6.3.2, May 1st, 2020
OS Version | KDE Flatpak runtime
Active python plugins | FreehandRasterGeoreferencer; quick_map_services; DigitizingTools; plaingeometryeditor; changeDataSource; QuickOSM; EasyCustomLabeling; splitmultipart; freehandEditing3; MetaSearch; db_manager

**Comment by nyalldawson** [comment]
QScintilla is, but the python bindings for it are missing. Try installing the "python3-pyqt5.qsci" package

**Comment by sk-dataocean-online** [comment]
I've made "apt install python3-pyqt5.qsci" but the errors remain.
BTW, the same issue was opened at flatpak: https://github.com/flathub/org.qgis.qgis/issues/79
