### ISSUE TITLE
Gdal2xyz do not allow choose the band in batch mode

### ISSUE THREAD

**Issue by jonnyforestGIS** [qgis/QGIS#31050]
- [x] Search through existing issue reports and gis.stackexchange.com to check whether the issue already exists
- [x] Test with a [clean new user profile](https://docs.qgis.org/testing/en/docs/user_manual/introduction/qgis_configuration.html?highlight=profile#working-with-user-profiles).
- [ ] Create a light and self-contained sample dataset and project file which demonstrates the issue

**Describe the bug**
The tool gdal2xyz give an error when we try to do the batch mode.

**How to Reproduce QGIS 3.4.9**

![gdal2xyzQGIS349](https://user-images.githubusercontent.com/4480601/62367854-b283ac00-b522-11e9-9749-dfb9a10c4bb1.gif)

1. Open QGIS and load some raster layers;
2. Open GDAl2xyz in Processing and toggle batch mode.
3. Define outputs and click Run.
4. See error error QGIS 3.4.9.

**Error in QGIS 3.4.9**
```python
2019-08-02T12:16:10     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\BatchPanel.py", line 224, in save
              widget = wrapper.wrappedWidget()
             AttributeError: 'NoneType' object has no attribute 'wrappedWidget'
             
2019-08-02T12:16:13     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\BatchAlgorithmDialog.py", line 88, in runAlgorithm
              parameters[param.name()] = wrapper.parameterValue()
             AttributeError: 'NoneType' object has no attribute 'parameterValue'
             
2019-08-02T12:16:13     WARNING    Traceback (most recent call last):
              File "C:/OSGEO4~1/apps/qgis-ltr/./python/plugins\processing\gui\BatchAlgorithmDialog.py", line 88, in runAlgorithm
              parameters[param.name()] = wrapper.parameterValue()
             AttributeError: 'NoneType' object has no attribute 'parameterValue'

```
**How to Reproduce in QGIS 3.8.0**

![gdal2xyzQGIS380](https://user-images.githubusercontent.com/4480601/62367832-a26bcc80-b522-11e9-8124-5be1560ad6d9.gif)

1. Open QGIS and load some raster layers;
2. Open GDAl2xyz in Processing and toggle batch mode.
3. See error error QGIS 3.8.0.
**Error in QGIS 3.8.0**
```python
AttributeError: 'BatchInputSelectionPanel' object has no attribute 'value' 
Traceback (most recent call last):
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 209, in widgetValue
    return self.value()
  File "C:/OSGEO4~1/apps/qgis/./python/plugins\processing\gui\wrappers.py", line 1012, in value
    return self.widget.value()
AttributeError: 'BatchInputSelectionPanel' object has no attribute 'value'
```

**QGIS and OS versions**
Tested on 3.4.9 and 3.8.0 64-bits

QGIS version | 3.4.9-Madeira | QGIS code revision | 54585165bb
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 520 | Running against PROJ | 5.2.0

-----------------------------------------------------------------------

QGIS version | 3.8.0-Zanzibar | QGIS code revision | 11aff65f10
-- | -- | -- | --
Compiled against Qt | 5.11.2 | Running against Qt | 5.11.2
Compiled against GDAL/OGR | 2.4.1 | Running against GDAL/OGR | 2.4.1
Compiled against GEOS | 3.7.2-CAPI-1.11.0 | Running against GEOS | 3.7.2-CAPI-1.11.0 b55d2125
PostgreSQL Client Version | 9.2.4 | SpatiaLite Version | 4.3.0
QWT Version | 6.1.3 | QScintilla2 Version | 2.10.8
Compiled against PROJ | 5.2.0 | Running against PROJ | Rel. 5.2.0, September 15th, 2018
OS Version | Windows 7 SP 1 (6.1) |   |  

**Additional context**
I will try to test in  QGIS 3.4.10 if this have some kind of error. Please let me know if I'm doing some kind of mistake.

Regards

**Comment by jonnyforestGIS** [comment]
[Feedback] After updated my QGIS version to 3.4.10 the problem in batch mode is different don't let me choose the band as result the batch can be executed but don't do anything because assume -1 as band number.

**Comment by alexbruy** [comment]
Duplicates #30671. Please search existing issues before opening new ticket.

**Comment by jonnyforestGIS** [comment]
@alexbruy I did the search but not relate with the #30671  my bad, sorry for the noise.
