### PR TITLE
fix downcasting with recent SIP versions

### PR DESCRIPTION
**Pull request by 3nids**
for instance in 3.22:

```
root = iface.layerTreeView().model().rootGroup()
AttributeError: 'QSortFilterProxyModel' object has no attribute 'rootGroup'
```

while it's working in 3.16 (windows).

### CODE REVIEW

**Comment by 3nids** [comment]
This doesn't work.

I guess ConvertToSubClassCode has to be written in the parent class.
I wonder if the existing ConvertToSubClassCode in child classes had any effect in the past?

**Comment by nyalldawson** [comment]
> I wonder if the existing ConvertToSubClassCode in child classes had any effect in the past?

It does, because when we're overriding a qt base class we could handle this outside the base class.

**Comment by 3nids** [comment]
But in the case of the layer tree model, are we doing something wrong? why was it working before and not anymore?
Should we reimplement the model() method and return the derived base class?

**Comment by nyalldawson** [comment]
@3nids 

> root = iface.layerTreeView().model().rootGroup()

The model is a QgsLayerTreeProxyModel, and there's no sip casting code for that class in place.
