### ISSUE TITLE
macOS: Symbol not found: __cg_jpeg_resync_to_restart when reprojecting raster layer with GDAL warp on macOS

### ISSUE THREAD

**Issue by carolineheitz** [qgis/QGIS#40164]
I work with Mac OX mojave with 3.17 and have this error when trying to reproject a raster map (but I've tried already to downgrade to 3.16, 3.12, 3.10 - same result):

Symbol not found: __cg_jpeg_resync_to_restart

```
GIS-Version: 3.17.0-Master
QGIS-Codeversion: 21908f09f5
Qt-Version: 5.14.2
GDAL-Version: 3.1.2
GEOS-Version: 3.8.1-CAPI-1.13.3
PROJ-Version: Rel. 6.3.2, May 1st, 2020
PDAL version: 2.2.0 (git-version: Release)
Verarbeite Algorithmus…
Algorithmus Transformieren (Reprojizieren) startet…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : '/Users/carolineheitz/Downloads/srtm_38_03/srtm_38_03.tif', 'MULTITHREADING' : False, 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RESAMPLING' : 0, 'SOURCE_CRS' : QgsCoordinateReferenceSystem('EPSG:4326'), 'TARGET_CRS' : QgsCoordinateReferenceSystem('EPSG:2056'), 'TARGET_EXTENT' : None, 'TARGET_EXTENT_CRS' : None, 'TARGET_RESOLUTION' : None }

GDAL command:
gdalwarp -s_srs EPSG:4326 -t_srs EPSG:2056 -r near -of GTiff /Users/carolineheitz/Downloads/srtm_38_03/srtm_38_03.tif /private/var/folders/0p/1r28hccn2hs1psvv25d_dxdr0000gn/T/processing_UAgcrX/8a4455ecec78469db7855bc5d0f8bf1c/OUTPUT.tif
GDAL command output:
dyld: Symbol not found: __cg_jpeg_resync_to_restart

Referenced from: /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

Expected in: /Volumes/QGIS.app/QGIS.app/Contents/MacOS/lib/libjpeg.9.dylib

in /System/Library/Frameworks/ImageIO.framework/Versions/A/ImageIO

Execution completed in 2.37 seconds
Results:
{'OUTPUT': '/private/var/folders/0p/1r28hccn2hs1psvv25d_dxdr0000gn/T/processing_UAgcrX/8a4455ecec78469db7855bc5d0f8bf1c/OUTPUT.tif'}

Lade Ergebnis Layer
Die folgenden Layer wurden nicht erzeugt.
• /private/var/folders/0p/1r28hccn2hs1psvv25d_dxdr0000gn/T/processing_UAgcrX/8a4455ecec78469db7855bc5d0f8bf1c/OUTPUT.tif
Im 'Protokoll-Fenster' im QGIS-Hauptfenster sind mehr Informationen zur Ausführung des Algorithmus zu finden.
```

____

I would be very happy to get some help on this, thank you!!

**Comment by roya0045** [comment]
https://stackoverflow.com/questions/35509731/dyld-symbol-not-found-cg-jpeg-resync-to-restart should help

**Comment by carolineheitz** [comment]
Thanks a lot for the hint, I had already seen the site, but I don't use the Qt-Creator (1). Furthermore I'm afraid that I might have undesired side effects by overwriting the libraries (2). Answer 3 was marked as not successful and I didn't use HomeBrew either (4). Therefore I have contacted you.

**Comment by MartinHinz** [comment]
I am a co-worker of Caroline. We currently kind of 'solved' it by using the Installer provided by KyngChaos for MacOS, but I have the feeling that this should also be fixed in the official repository, since it claims to be compatible to 10.13+. If there are any further information that might help you fixing the issue, we would be more than happy to assist.

**Comment by gioman** [comment]
> I am a co-worker of Caroline. We currently kind of 'solved' it by using the Installer provided by KyngChaos for MacOS, but I have the feeling that this should also be fixed in the official repository, since it claims to be compatible to 10.13+. If there are any further information that might help you fixing the issue, we would be more than happy to assist.

@MartinHinz I will check if I can replicate on my mac mini with Catalina.

**Comment by MartinHinz** [comment]
Thank you very much, much appreciated!

**Comment by PeterPetrik** [comment]
@carolineheitz @MartinHinz can you please try with 3.21.0 nightly build https://qgis.org/downloads/macos/nightly/qgis_nightly_master_20210916_124111.dmg ? I am able to use GDAL warp without any issue. 

If it does not work for you ,can you please give me some example data?

```
QGIS version: 3.21.0-Master
QGIS code revision: 5ea353ba22
Qt version: 5.15.2
Python version: 3.9.5
GDAL version: 3.3.2
GEOS version: 3.9.1-CAPI-1.14.2
PROJ version: Rel. 8.1.1, September 1st, 2021
PDAL version: 2.3.0 (git-version: Release)
Processing algorithm…
Algorithm 'Warp (reproject)' starting…
Input parameters:
{ 'DATA_TYPE' : 0, 'EXTRA' : '', 'INPUT' : '/Users/peter/Projects/qgis1/QGIS/tests/testdata/raster/raster-palette-crash2.tif', 'MULTITHREADING' : False, 'NODATA' : None, 'OPTIONS' : '', 'OUTPUT' : 'TEMPORARY_OUTPUT', 'RESAMPLING' : 0, 'SOURCE_CRS' : None, 'TARGET_CRS' : QgsCoordinateReferenceSystem('EPSG:2169'), 'TARGET_EXTENT' : None, 'TARGET_EXTENT_CRS' : None, 'TARGET_RESOLUTION' : None }

GDAL command:
gdalwarp -t_srs EPSG:2169 -r near -of GTiff /Users/peter/Projects/qgis1/QGIS/tests/testdata/raster/raster-palette-crash2.tif /private/var/folders/q8/6bcx7kkn31z1bksknbqrgy1c0000gn/T/processing_cMnIAJ/3609ba17597949b7b0e09b6bf19a42d7/OUTPUT.tif
GDAL command output:
Creating output file that is 24P x 24L.
Processing /Users/peter/Projects/qgis1/QGIS/tests/testdata/raster/raster-palette-crash2.tif [1/1] : 0Using internal nodata values (e.g. nan) for image /Users/peter/Projects/qgis1/QGIS/tests/testdata/raster/raster-palette-crash2.tif.
Copying nodata values from source /Users/peter/Projects/qgis1/QGIS/tests/testdata/raster/raster-palette-crash2.tif to destination /private/var/folders/q8/6bcx7kkn31z1bksknbqrgy1c0000gn/T/processing_cMnIAJ/3609ba17597949b7b0e09b6bf19a42d7/OUTPUT.tif.
...10...20...30...40...50...60...70...80...90...100 - done.
Process completed successfully
Execution completed in 0.28 seconds
Results:
{'OUTPUT': '/private/var/folders/q8/6bcx7kkn31z1bksknbqrgy1c0000gn/T/processing_cMnIAJ/3609ba17597949b7b0e09b6bf19a42d7/OUTPUT.tif'}

Loading resulting layers
Algorithm 'Warp (reproject)' finished
```
